Repository moderntribe/events-gutenberg, pull requests merged in 2018-07, with the labels that each got.

#126 Connect EventDateTime block with new store
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-website/block.js
  src/modules/data/blocks/datetime/actions.js
  src/modules/data/blocks/datetime/index.js
  src/modules/data/blocks/datetime/reducers.js
  src/modules/data/blocks/datetime/selectors.js
  src/modules/data/blocks/datetime/separators/reducers.js
  src/modules/data/blocks/datetime/separators/types.js
  src/modules/data/blocks/datetime/types.js
  src/modules/data/blocks/datetime/values/reducers.js
  src/modules/data/blocks/datetime/variants/reducers.js
  src/modules/data/blocks/index.js
  src/modules/data/blocks/middlewares/allday.js
  src/modules/data/blocks/middlewares/date.js
  src/modules/data/blocks/middlewares/index.js
  src/modules/data/blocks/middlewares/multiday.js
  src/modules/data/blocks/middlewares/time.js
  src/modules/data/blocks/organizers/index.js
  src/modules/data/blocks/price/actions.js
  src/modules/data/blocks/price/index.js
  src/modules/data/blocks/price/reducers.js
  src/modules/data/blocks/price/types.js
  src/modules/data/blocks/reducers.js
  src/modules/data/blocks/venue/index.js
  src/modules/data/blocks/website/actions.js
  src/modules/data/blocks/website/index.js
  src/modules/data/blocks/website/reducers.js
  src/modules/data/blocks/website/types.js
  src/modules/data/index.js
  src/modules/data/reducers.js
  src/modules/data/ui/actions.js
  src/modules/data/ui/index.js
  src/modules/data/ui/reducer.js
  src/modules/data/ui/selectors.js
  src/modules/data/ui/types.js
  src/modules/elements/month/element.js
  src/modules/elements/time-picker/element.js
Labels: review:merge

#127 fix website block background and border
  src/modules/blocks/event-website/style.pcss
Labels: review:merge

#128 fix font size for tag and category block
  src/modules/blocks/event-category/style.pcss
  src/modules/blocks/event-tags/style.pcss
  src/modules/elements/terms-list/style.pcss
Labels: review:merge

#132 Allow sync of blocks
  src/modules/blocks/event-datetime/block.js
  src/modules/editor/hoc/with-save-data.js
  src/modules/editor/hoc/with-store.js
Labels: review:merge

#131 Compatibility for Event Tickets
  src/Tribe/Compatibility/Tickets.php
  src/Tribe/Provider.php
  src/modules/editor/style.pcss
Labels: review:merge, status:code-review

#134 set flex for svg so it does not shrink
  src/modules/blocks/event-links/style.pcss
Labels: review:merge, status:code-review

#136 Create a CSS base to work our FE views.
  events-gutenberg.php
  src/Tribe/Assets.php
  src/modules/views/classic-event-details/style.pcss
  src/modules/views/event-category/style.pcss
  src/modules/views/event-datetime/style.pcss
  src/modules/views/event-links/style.pcss
  src/modules/views/event-organizer/style.pcss
  src/modules/views/event-price/style.pcss
  src/modules/views/event-tags/style.pcss
  src/modules/views/event-venue/style.pcss
  src/modules/views/event-website/style.pcss
  src/modules/views/index.js
  src/modules/views/style.pcss
  webpack.config.js
Labels: review:merge

#133 Actual Classic content gets migrated in Gutenberg loading
  src/Tribe/Editor.php
  src/Tribe/Provider.php
Labels: review:merge, status:code-review

#135 Remove duplication of stores for search
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-venue/block.js
  src/modules/data/index.js
  src/modules/data/reducers.js
  src/modules/data/request/actions.js
  src/modules/data/request/index.js
  src/modules/data/request/middlewares/index.js
  src/modules/data/request/middlewares/wp-request.js
  src/modules/data/request/types.js
  src/modules/data/request/utils.js
  src/modules/data/search/actions.js
  src/modules/data/search/index.js
  src/modules/data/search/reducers.js
  src/modules/data/search/reducers/search.js
  src/modules/data/search/selector.js
  src/modules/data/search/types.js
  src/modules/editor/hoc/with-properties.js
  src/modules/editor/hoc/with-save-data.js
  src/modules/editor/post-types.js
  src/modules/elements/search-or-create/element.js
Labels: review:merge

#145 Fix organizer block on initialize and venue defaults
  readme.md
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-venue/block.js
  src/modules/data/blocks/organizers/selectors.js
  src/modules/data/blocks/venue/reducers.js
  src/modules/data/blocks/venue/selectors.js
  src/modules/data/request/utils.js
  src/modules/editor/hoc/with-details.js
  src/modules/elements/search-or-create/element.js
Labels: status:code-review

#146 Prevent to create multiple entries and remove publish posts
  readme.md
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-venue/block.js
  src/modules/data/forms/actions.js
  src/modules/data/forms/reducer.js
  src/modules/data/forms/reducers/form.js
  src/modules/data/forms/selectors.js
  src/modules/data/forms/types.js
  src/modules/editor/hoc/with-form.js
Labels: review:merge

#147 Favor `<AutosizeInput` instead of `<RichText>`
  readme.md
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/style.pcss
Labels: review:merge

#148 Fix count of blocks of the same type
  readme.md
  src/modules/editor/hoc/with-form.js
  src/modules/editor/hoc/with-save-data.js
Labels: review:merge

#142 Implement attributes wrapper for views
  src/Tribe/Blocks/Abstract.php
  src/Tribe/Blocks/Classic_Event_Details.php
  src/Tribe/Blocks/Event_Category.php
  src/Tribe/Blocks/Event_Datetime.php
  src/Tribe/Blocks/Event_Links.php
  src/Tribe/Blocks/Event_Organizer.php
  src/Tribe/Blocks/Event_Price.php
  src/Tribe/Blocks/Event_Tags.php
  src/Tribe/Blocks/Event_Venue.php
  src/Tribe/Blocks/Event_Website.php
  src/Tribe/Blocks/Featured_Image.php
  src/Tribe/Blocks/Interface.php
  src/Tribe/Template.php
Labels: review:merge

#124 Fix/108301 price block issues
  readme.md
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/style.pcss
  src/modules/elements/dashboard/style.pcss
Labels: review:merge, status:code-review

#125 Fix/108300 date time block fixes
  readme.md
  src/Tribe/Editor.php
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-datetime/style.pcss
  src/modules/editor/utils/date.js
  src/modules/editor/utils/moment.js
  src/modules/elements/month/element.js
  src/modules/elements/month/style.pcss
  src/modules/elements/time-picker/style.pcss
Labels: review:merge

#151 fix/108303 fix textbox width
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-links/style.pcss
Labels: review:merge, status:code-review

#153 Add Time input in Dashboard
  readme.md
  src/modules/blocks/event-datetime/style.pcss
  src/modules/data/blocks/middlewares/date.js
  src/modules/data/blocks/middlewares/multiday.js
  src/modules/data/blocks/middlewares/time.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/time-picker/style.pcss
Labels: review:merge

#152 Implement the event links block frontend view
  readme.md
  src/Tribe/Blocks/Event_Links.php
  src/modules/views/event-links/style.pcss
  src/views/blocks/event-links.php
Labels: review:merge

#154 Fix edge cases and jumps of days when is not multiday
  src/modules/blocks/event-datetime/block.js
  src/modules/data/blocks/middlewares/time.js
  src/modules/editor/utils/moment.js
  src/modules/elements/time-picker/element.js
Labels: review:merge

#139 Implement the event website block frontend view
  readme.md
  src/Tribe/Blocks/Event_Website.php
  src/modules/views/event-website/style.pcss
  src/views/blocks/event-website.php
Labels: review:merge

#140 Implement price block view
  readme.md
  src/Tribe/Blocks/Event_Price.php
  src/modules/views/event-price/style.pcss
  src/views/blocks/event-price.php
Labels: review:merge

#137 Implement organizer block view
  readme.md
  src/modules/views/event-organizer/style.pcss
  src/views/blocks/event-organizer.php
Labels: review:merge

#150 Implement the event venue block frontend view
  readme.md
  src/modules/views/event-venue/style.pcss
  src/views/blocks/event-venue.php
  src/views/blocks/parts/map.php
  src/views/blocks/parts/venue.php
Labels: review:merge, status:code-review

#155 Prevent overflow on iCal link
  src/modules/blocks/event-links/block.js
Labels: review:merge

#157 Fixes for views
  src/modules/views/style.pcss
  src/views/blocks/event-links.php
Labels: review:merge, status:code-review

#158 Fix default timezone value when new event was created
  readme.md
  src/modules/data/blocks/datetime/reducers.js
  src/modules/editor/utils/date.js
Labels: status:code-review

#159 Fix linter issues
  .eslintrc.json
  src/modules/blocks/classic-event-details/organizer/item.js
  src/modules/blocks/classic-event-details/organizers.js
  src/modules/blocks/event-category/index.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-venue/venue.js
  src/modules/blocks/featured-image/block.js
  src/modules/data/blocks/middlewares/date.js
  src/modules/data/blocks/organizers/reducers/block.js
  src/modules/data/request/middlewares/wp-request.js
  src/modules/data/search/actions.js
  src/modules/editor/hoc/with-details.js
  src/modules/elements/date-picker/element.js
  src/modules/elements/input/element.js
  src/modules/elements/loading/index.js
  src/modules/elements/meta-group/element.js
  src/modules/elements/month/element.js
  src/modules/elements/organizer-form/element.js
  src/modules/elements/search-or-create/element.js
  src/modules/elements/search-posts/element.js
  src/modules/elements/terms-list/element.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/year-month-form/element.js
  src/modules/views/index.js
Labels: status:code-review

#160 Fix/109288 revert to venue
  readme.md
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/elements/google-map/element.js
Labels: review:merge, status:code-review

#161 Add in @babel/runtime package to fix build error
  package.json
Labels: review:merge, status:code-review, type:bug

#162 Add tests for utils functions
  .eslintrc.json
  jest.globals.js
  package.json
  readme.md
  src/modules/editor/index.js
  src/modules/editor/settings.js
  src/modules/editor/tests/post-types.test.js
  src/modules/editor/tests/settings.test.js
  src/modules/editor/utils/dom.js
  src/modules/editor/utils/geo-data.js
  src/modules/editor/utils/globals.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/object.js
  src/modules/editor/utils/request.js
  src/modules/editor/utils/string.js
  src/modules/editor/utils/tests/array.test.js
  src/modules/editor/utils/tests/date.test.js
  src/modules/editor/utils/tests/dom.test.js
  src/modules/editor/utils/tests/geo-data.test.js
  src/modules/editor/utils/tests/globals.test.js
  src/modules/editor/utils/tests/input.test.js
  src/modules/editor/utils/tests/moment.test.js
  src/modules/editor/utils/tests/object.test.js
  src/modules/editor/utils/tests/range.test.js
  src/modules/editor/utils/tests/string.test.js
  src/modules/editor/utils/tests/time.test.js
  src/modules/elements/google-map/element.js
Labels: review:merge

#164 Update render for the SVG icon
  src/resources/icons/tec.svg
Labels: review:merge

#165 Standarize the name used to storage tests
  src/modules/editor/__tests__/post-types.test.js
  src/modules/editor/__tests__/settings.test.js
  src/modules/editor/utils/__tests__/array.test.js
  src/modules/editor/utils/__tests__/date.test.js
  src/modules/editor/utils/__tests__/dom.test.js
  src/modules/editor/utils/__tests__/geo-data.test.js
  src/modules/editor/utils/__tests__/globals.test.js
  src/modules/editor/utils/__tests__/input.test.js
  src/modules/editor/utils/__tests__/moment.test.js
  src/modules/editor/utils/__tests__/object.test.js
  src/modules/editor/utils/__tests__/range.test.js
  src/modules/editor/utils/__tests__/string.test.js
  src/modules/editor/utils/__tests__/time.test.js
Labels: review:merge, status:code-review

#166 Add tests for the UI and Search actions
  .eslintrc.json
  package.json
  src/modules/data/search/__tests__/actions.test.js
  src/modules/data/ui/__tests__/actions.test.js
  src/modules/editor/__tests__/post-types.test.js
  src/modules/editor/__tests__/settings.test.js
  src/modules/editor/utils/__tests__/array.test.js
  src/modules/editor/utils/__tests__/date.test.js
  src/modules/editor/utils/__tests__/dom.test.js
  src/modules/editor/utils/__tests__/geo-data.test.js
  src/modules/editor/utils/__tests__/globals.test.js
  src/modules/editor/utils/__tests__/input.test.js
  src/modules/editor/utils/__tests__/moment.test.js
  src/modules/editor/utils/__tests__/object.test.js
  src/modules/editor/utils/__tests__/range.test.js
  src/modules/editor/utils/__tests__/string.test.js
  src/modules/editor/utils/__tests__/time.test.js
Labels: review:merge

#167 Add tests for UI: reducer, selector and type
  package.json
  src/modules/data/search/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/search/__tests__/actions.test.js
  src/modules/data/ui/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/ui/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/ui/__tests__/actions.test.js
  src/modules/data/ui/__tests__/reducer.test.js
  src/modules/data/ui/__tests__/selectors.test.js
  src/modules/data/ui/__tests__/types.test.js
Labels: review:merge

#168 Add tests for the website block
  src/modules/data/blocks/website/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/website/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/website/__tests__/actions.test.js
  src/modules/data/blocks/website/__tests__/reducers.test.js
  src/modules/data/blocks/website/__tests__/selectors.test.js
  src/modules/data/blocks/website/__tests__/types.test.js
  src/modules/data/blocks/website/selectors.js
  src/modules/data/ui/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/ui/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/ui/__tests__/actions.test.js
  src/modules/data/ui/__tests__/reducer.test.js
Labels: review:merge

#169 Add tests for Price: Actions, Reducer, Types, Selectors
  src/modules/data/blocks/price/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/price/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/price/__tests__/actions.test.js
  src/modules/data/blocks/price/__tests__/reducers.test.js
  src/modules/data/blocks/price/__tests__/selectors.test.js
  src/modules/data/blocks/price/__tests__/types.test.js
  src/modules/data/blocks/price/selectors.js
  src/modules/data/blocks/selectors.js
Labels: review:merge

#170 Add tests for: Action, Selector, Reducer, Types for Sharing block
  src/modules/data/blocks/sharing/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/sharing/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/sharing/__tests__/actions.test.js
  src/modules/data/blocks/sharing/__tests__/reducer.test.js
  src/modules/data/blocks/sharing/__tests__/selectors.test.js
  src/modules/data/blocks/sharing/__tests__/types.test.js
  src/modules/data/blocks/sharing/actions.js
  src/modules/data/blocks/sharing/index.js
  src/modules/data/blocks/sharing/reducers.js
Labels: review:merge

#171 Add tests for types and selectors of search
  src/modules/data/search/__tests__/selectors.test.js
  src/modules/data/search/__tests__/types.test.js
  src/modules/data/search/selector.js
Labels: review:merge

#174 Add tests for classic: reducer, types, actions, selectors
  src/modules/data/blocks/classic/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/classic/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/classic/__tests__/actions.test.js
  src/modules/data/blocks/classic/__tests__/reducers.test.js
  src/modules/data/blocks/classic/__tests__/selectors.test.js
  src/modules/data/blocks/classic/__tests__/types.test.js
  src/modules/data/blocks/datetime/__tests__/reducers.test.js
Labels: status:code-review

#175 Avoid warnings of i18n module by creating a mock
  __mocks__/@wordpress/i18n.js
Labels: review:merge

#176 Add set of tests for Higher Order components.
  .babelrc
  .eslintrc.json
  jest.globals.js
  package.json
  src/modules/editor/hoc/__tests__/__snapshots__/with-details.test.js.snap
  src/modules/editor/hoc/__tests__/__snapshots__/with-form.test.js.snap
  src/modules/editor/hoc/__tests__/__snapshots__/with-save-data.test.js.snap
  src/modules/editor/hoc/__tests__/__snapshots__/with-store.test.js.snap
  src/modules/editor/hoc/__tests__/with-details.test.js
  src/modules/editor/hoc/__tests__/with-form.test.js
  src/modules/editor/hoc/__tests__/with-save-data.test.js
  src/modules/editor/hoc/__tests__/with-store.test.js
  src/modules/editor/hoc/with-form.js
Labels: status:code-review

#177 Add tests for Request
  jest.globals.js
  src/modules/data/request/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/request/__tests__/actions.test.js
  src/modules/data/request/__tests__/types.test.js
  src/modules/data/request/__tests__/utils.test.js
  src/modules/data/request/index.js
  src/modules/data/request/middlewares/__tests__/wp-request.test.js
  src/modules/data/request/middlewares/wp-request.js
  src/modules/editor/utils/request.js
Labels: review:merge

#178 Add set of tests for the data utils
  src/modules/data/__tests__/utils.test.js
Labels: review:merge

#179 Add tests for the time middleware
  src/modules/data/blocks/middlewares/__tests__/time.test.js
  src/modules/data/blocks/middlewares/time.js
Labels: review:merge

#180 Add tests for all day middleware
  src/modules/data/blocks/middlewares/__tests__/allday.test.js
Labels: review:merge

#181 110839/test dates middleware
  src/modules/data/blocks/middlewares/__tests__/dates.test.js
  src/modules/data/blocks/middlewares/dates.js
  src/modules/data/blocks/middlewares/index.js
Labels: review:merge, status:code-review

#183 Change featured image placeholder text
  src/modules/blocks/featured-image/block.js
Labels: review:merge

#184 110839/test search actions
  src/modules/data/search/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/search/__tests__/actions.test.js
  src/modules/data/search/__tests__/reducers.test.js
  src/modules/data/search/reducers/__tests__/__snapshots__/search.test.js.snap
  src/modules/data/search/reducers/__tests__/search.test.js
Labels: review:merge

#185 110839/test data details
  src/modules/data/details/__tests__/__snapshots__/actions.js.snap
  src/modules/data/details/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/details/__tests__/actions.js
  src/modules/data/details/__tests__/reducer.test.js
  src/modules/data/details/__tests__/selectors.test.js
  src/modules/data/details/__tests__/types.test.js
  src/modules/data/details/reducers/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/details/reducers/__tests__/details.test.js
  src/modules/data/details/selectors.js
  src/modules/data/details/types.js
Labels: review:merge

#144 fix/108550 venue block fe
  src/views/blocks/parts/map.php
Labels: review:merge

#186 Add "Event Blocks" category to the editor.
  readme.md
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/event-category/index.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-website/index.js
Labels: review:merge

#190 Normalize styles for the Event Options metabox
  readme.md
  src/modules/editor/style.pcss
Labels: review:merge

#156 Fix/108306 date time dashboard closing
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-price/block.js
  src/modules/data/ui/actions.js
  src/modules/data/ui/reducer.js
  src/modules/data/ui/selectors.js
  src/modules/data/ui/types.js
  src/modules/elements/dashboard/element.js
  src/modules/elements/dashboard/style.pcss
  src/modules/elements/time-picker/element.js
Labels: review:merge

#187 Add set of tests for the Form reducer
  src/modules/data/forms/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/forms/__tests__/actions.test.js
  src/modules/data/forms/__tests__/reducer.test.js
  src/modules/data/forms/__tests__/selectors.test.js
  src/modules/data/forms/__tests__/types.js
  src/modules/data/forms/reducers/__tests__/__snapshots__/form.test.js.snap
  src/modules/data/forms/reducers/__tests__/form.test.js
  src/modules/data/forms/reducers/__tests__/volatile.test.js
Labels: review:merge

#189 Adjust code and tests to follow WP signature
  src/modules/data/request/middlewares/__tests__/wp-request.test.js
  src/modules/data/request/middlewares/wp-request.js
Labels: review:merge

#188 Add tests for the data/organizer reducer
  src/modules/data/blocks/organizers/__tests__/__snapshots__/actions.js.snap
  src/modules/data/blocks/organizers/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/organizers/__tests__/actions.js
  src/modules/data/blocks/organizers/__tests__/selectors.test.js
  src/modules/data/blocks/organizers/__tests__/types.test.js
  src/modules/data/blocks/organizers/reducers/__tests__/block.test.js
  src/modules/data/blocks/organizers/reducers/__tests__/blocks.test.js
  src/modules/data/blocks/organizers/reducers/__tests__/classic.test.js
  src/modules/data/blocks/organizers/reducers/block.js
  src/modules/data/blocks/organizers/reducers/blocks.js
  src/modules/data/ui/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/ui/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/ui/__tests__/actions.test.js
  src/modules/data/ui/__tests__/reducer.test.js
  src/modules/data/ui/__tests__/selectors.test.js
Labels: review:merge

#194 Update tests to prevent errors on snapshots
  jest.setup.js
  package.json
  src/modules/data/ui/actions.js
Labels: status:code-review

#193 Eslint config and travis support
  .travis.yml
  jest.setup.js
  package.json
  src/modules/data/ui/actions.js
Labels: review:merge

#196 [Sharing Links] Pass the attributes to the view
  src/Tribe/Blocks/Event_Links.php
Labels: review:merge

#197 Remove clear button from time inputs (webkit)
  src/modules/elements/time-picker/style.pcss
Labels: review:merge

#198 Use DBA format for dates when saving into the store
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/event-datetime/block.js
  src/modules/data/blocks/datetime/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/datetime/__tests__/__snapshots__/reducers.test.js.snap
  src/modules/data/blocks/datetime/__tests__/actions.test.js
  src/modules/data/blocks/datetime/actions.js
  src/modules/data/blocks/middlewares/__tests__/allday.test.js
  src/modules/data/blocks/middlewares/__tests__/dates.test.js
  src/modules/data/blocks/middlewares/__tests__/multiday.test.js
  src/modules/data/blocks/middlewares/__tests__/time.test.js
  src/modules/data/ui/actions.js
  src/modules/editor/style.pcss
  src/modules/editor/utils/__tests__/date.test.js
  src/modules/editor/utils/__tests__/dom.test.js
  src/modules/editor/utils/__tests__/moment.test.js
  src/modules/editor/utils/date.js
  src/modules/editor/utils/dom.js
  src/modules/editor/utils/moment.js
Labels: status:code-review
