Repository moderntribe/events-gutenberg, pull requests merged in 2018-09, with the labels that each got.

#287 Setup basic store shape for tickets
  plugins/tickets/.gitignore
  plugins/tickets/scripts/linkDependencies
  plugins/tickets/src/modules/blocks/index.js
  plugins/tickets/src/modules/data/__tests__/prefix.test.js
  plugins/tickets/src/modules/data/index.js
  plugins/tickets/src/modules/data/prefix.js
  plugins/tickets/src/modules/data/reducers.js
  readme.md
Labels: review:merge, status:code-review

#284 Add AJAX availability check for the tickets FE
  src/Tribe/Blocks/Tickets.php
  src/resources/js/tickets.js
  src/views/blocks/tickets/extra-available.php
  src/views/blocks/tickets/item.php
Labels: review:question, status:code-review

#293 Accept a `[200, 300)` response codes on request
  plugins/common/src/modules/store/middlewares/request/__tests__/wp-request.test.js
  plugins/common/src/modules/store/middlewares/request/wp-request.js
  plugins/events/src/modules/data/forms/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/forms/__tests__/actions.test.js
  plugins/events/src/modules/data/forms/actions.js
  plugins/events/src/modules/elements/organizer-form/element.js
  readme.md
Labels: review:merge

#289 Update icons from alias to module
  .gitignore
  package-lock.json
  plugins/common/.gitignore
  plugins/common/scripts/linkDependencies
  plugins/common/src/modules/elements/block-icon/index.js
  plugins/common/src/modules/elements/block-icon/style.pcss
  plugins/common/src/modules/elements/icons/element.js
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/icons/alert.svg
  plugins/common/src/modules/icons/clipboard.svg
  plugins/common/src/modules/icons/cog.svg
  plugins/common/src/modules/icons/cross.svg
  plugins/common/src/modules/icons/index.js
  plugins/common/src/modules/icons/info.svg
  plugins/common/src/modules/icons/pencil.svg
  plugins/common/src/modules/icons/tag.svg
  plugins/common/src/modules/icons/tec.svg
  plugins/common/src/modules/icons/user.svg
  plugins/common/webpack.config.js
  plugins/events/.gitignore
  plugins/events/scripts/linkDependencies
  plugins/events/src/modules/blocks/classic-event-details/index.js
  plugins/events/src/modules/blocks/event-category/index.js
  plugins/events/src/modules/blocks/event-datetime/index.js
  plugins/events/src/modules/blocks/event-links/index.js
  plugins/events/src/modules/blocks/event-links/template.js
  plugins/events/src/modules/blocks/event-organizer/details/index.js
  plugins/events/src/modules/blocks/event-organizer/index.js
  plugins/events/src/modules/blocks/event-organizer/template.js
  plugins/events/src/modules/blocks/event-price/index.js
  plugins/events/src/modules/blocks/event-tags/index.js
  plugins/events/src/modules/blocks/event-venue/index.js
  plugins/events/src/modules/blocks/event-venue/template.js
  plugins/events/src/modules/blocks/event-website/index.js
  plugins/events/src/modules/blocks/featured-image/index.js
  plugins/events/src/modules/elements/checkbox/element.js
  plugins/events/src/modules/icons/checkbox-off.svg
  plugins/events/src/modules/icons/checkbox-on.svg
  plugins/events/src/modules/icons/index.js
  plugins/events/src/modules/icons/link.svg
  plugins/events/src/modules/icons/organizer.svg
  plugins/events/src/modules/icons/venue.svg
  plugins/events/src/resources/icons/close.svg
  plugins/events/src/views/blocks/event-links.php
  plugins/events/webpack.config.js
  plugins/tickets/.gitignore
  plugins/tickets/scripts/linkDependencies
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/icons/active/clock.svg
  plugins/tickets/src/modules/icons/active/rsvp.svg
  plugins/tickets/src/modules/icons/active/ticket.svg
  plugins/tickets/src/modules/icons/inactive/clock.svg
  plugins/tickets/src/modules/icons/inactive/rsvp.svg
  plugins/tickets/src/modules/icons/inactive/ticket.svg
  plugins/tickets/src/modules/icons/index.js
  plugins/tickets/webpack.config.js
  readme.md
  webpack/common/webpack.config.js
Labels: status:code-review

#291 Create component for ticket icon
  plugins/tickets/src/Tribe/Assets.php
  plugins/tickets/src/modules/blocks/tickets/DisabledTickets.js
  plugins/tickets/src/modules/blocks/tickets/TicketIcon.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/DisabledTicket.test.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/TicketIcon.test.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/DisabledTicket.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/TicketIcon.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  readme.md
Labels: review:merge

#296 Load tickets blocks only on supported post types
  plugins/common/src/Tribe/Editor.php
  plugins/common/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events/src/Tribe/Editor.php
  plugins/events/src/Tribe/Provider.php
  plugins/tickets/src/Tribe/Assets.php
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Provider.php
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/index.js
Labels: review:merge

#295 Removal of icons, result from a merge operation
  plugins/tickets/src/resources/icons/checkmark.svg
  plugins/tickets/src/resources/icons/cross.svg
  plugins/tickets/src/resources/icons/rsvp.svg
  plugins/tickets/src/resources/icons/ticket.svg
Labels: status:code-review

#286 Task/113412 derive datetime data
  package-lock.json
  package.json
  plugins/common/src/modules/store/configureStore.js
  plugins/common/src/modules/store/index.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/container.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/template.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/container.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/template.js
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/actions.js
  plugins/events-pro/src/modules/data/blocks/exception/index.js
  plugins/events-pro/src/modules/data/blocks/exception/options.js
  plugins/events-pro/src/modules/data/blocks/exception/reducer.js
  plugins/events-pro/src/modules/data/blocks/exception/sagas.js
  plugins/events-pro/src/modules/data/blocks/exception/types.js
  plugins/events-pro/src/modules/data/blocks/index.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/index.js
  plugins/events-pro/src/modules/data/blocks/recurring/reducer.js
  plugins/events-pro/src/modules/data/blocks/recurring/sagas.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/data/blocks/recurring/types.js
  plugins/events-pro/src/modules/data/blocks/sagas.js
  plugins/events-pro/src/modules/data/ui/actions.js
  plugins/events-pro/src/modules/data/ui/reducer.js
  plugins/events-pro/src/modules/data/ui/types.js
  plugins/events-pro/src/modules/elements/add-field/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/add-field/element.js
  plugins/events-pro/src/modules/elements/add-field/style.pcss
  plugins/events-pro/src/modules/elements/date-picker-input/element.js
  plugins/events-pro/src/modules/elements/date-picker-input/style.pcss
  plugins/events-pro/src/modules/elements/exception-add-field/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/exception-field/element.js
  plugins/events-pro/src/modules/elements/exception-field/singular.js
  plugins/events-pro/src/modules/elements/exception-field/style.pcss
  plugins/events-pro/src/modules/elements/exception-form/element.js
  plugins/events-pro/src/modules/elements/fieldset/element.js
  plugins/events-pro/src/modules/elements/fieldset/style.pcss
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/label/element.js
  plugins/events-pro/src/modules/elements/label/style.pcss
  plugins/events-pro/src/modules/elements/panel-header/element.js
  plugins/events-pro/src/modules/elements/panel-header/style.pcss
  plugins/events-pro/src/modules/elements/recurring-add-field/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/recurring-field/element.js
  plugins/events-pro/src/modules/elements/recurring-field/singular.js
  plugins/events-pro/src/modules/elements/recurring-field/style.pcss
  plugins/events-pro/src/modules/elements/recurring-form/element.js
  plugins/events-pro/src/modules/elements/recurring-form/style.pcss
  plugins/events-pro/src/modules/elements/remove-field/element.js
  plugins/events-pro/src/modules/elements/remove-field/style.pcss
  plugins/events-pro/src/modules/elements/row/element.js
  plugins/events-pro/src/modules/elements/row/style.pcss
  plugins/events/src/modules/elements/time-picker/element.js
Labels: review:merge

#301 Do a shallow comparision between elements
  .eslintrc
  plugins/common/src/modules/hoc/__tests__/__snapshots__/with-save-data.test.js.snap
  plugins/common/src/modules/hoc/__tests__/with-save-data.test.js
  plugins/common/src/modules/hoc/with-save-data.js
  readme.md
Labels: review:merge

#300 Thunks to sagas price block
  package-lock.json
  package.json
  plugins/common/src/modules/store/configureStore.js
  plugins/common/src/modules/store/index.js
  plugins/events/src/modules/data/blocks/index.js
  plugins/events/src/modules/data/blocks/price/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/price/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/price/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/price/actions.js
  plugins/events/src/modules/data/blocks/price/index.js
  plugins/events/src/modules/data/blocks/price/sagas.js
  plugins/events/src/modules/data/blocks/price/types.js
  plugins/events/src/modules/data/blocks/sagas.js
Labels: review:merge

#303 Task/113725 thunks to sagas
  plugins/events/src/modules/data/blocks/classic/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/classic/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/classic/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/classic/actions.js
  plugins/events/src/modules/data/blocks/classic/index.js
  plugins/events/src/modules/data/blocks/classic/sagas.js
  plugins/events/src/modules/data/blocks/classic/types.js
  plugins/events/src/modules/data/blocks/sagas.js
  plugins/events/src/modules/data/blocks/sharing/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/sharing/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/sharing/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/sharing/actions.js
  plugins/events/src/modules/data/blocks/sharing/index.js
  plugins/events/src/modules/data/blocks/sharing/sagas.js
  plugins/events/src/modules/data/blocks/sharing/types.js
  plugins/events/src/modules/data/blocks/venue/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/venue/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/venue/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/venue/__tests__/selectors.test.js
  plugins/events/src/modules/data/blocks/venue/actions.js
  plugins/events/src/modules/data/blocks/venue/index.js
  plugins/events/src/modules/data/blocks/venue/sagas.js
  plugins/events/src/modules/data/blocks/venue/types.js
  plugins/events/src/modules/data/blocks/website/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/website/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/website/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/website/actions.js
  plugins/events/src/modules/data/blocks/website/index.js
  plugins/events/src/modules/data/blocks/website/sagas.js
  plugins/events/src/modules/data/blocks/website/types.js
Labels: review:merge

#304 Adding whitelist and packaging script
  package-lock.json
  package-whitelist.json
  package.json
  util/zip.js
Labels: review:merge

#297 Create container for the tickets block
  plugins/common/src/modules/elements/button/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/button/__tests__/element.test.js
  plugins/common/src/modules/elements/button/element.js
  plugins/common/src/modules/elements/button/style.pcss
  plugins/events/src/modules/editor/style.pcss
  plugins/tickets/src/modules/blocks/tickets/Container.js
  plugins/tickets/src/modules/blocks/tickets/Template.js
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  plugins/tickets/src/modules/elements/action-button/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/action-button/__tests__/element.test.js
  plugins/tickets/src/modules/elements/action-button/element.js
  plugins/tickets/src/modules/elements/action-button/style.pcss
  plugins/tickets/src/modules/elements/action-dashboard/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/action-dashboard/__tests__/element.test.js
  plugins/tickets/src/modules/elements/action-dashboard/element.js
  plugins/tickets/src/modules/elements/availability/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/availability/__tests__/element.test.js
  plugins/tickets/src/modules/elements/availability/element.js
  plugins/tickets/src/modules/elements/availability/style.pcss
  plugins/tickets/src/modules/elements/capacity-table/element.js
  plugins/tickets/src/modules/elements/index.js
  plugins/tickets/src/modules/elements/numeric-label/__tests__/__snapshots__/element.js.snap
  plugins/tickets/src/modules/elements/numeric-label/__tests__/element.js
  plugins/tickets/src/modules/elements/numeric-label/element.js
  readme.md
Labels: status:code-review

#308 Feature/112917 rsvp block
  plugins/tickets/src/modules/blocks/index.js
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/__tests__/index.test.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
Labels: review:merge

#311 Making Events Gutenberg compatible with Gutenberg 3.8
  package-lock.json
  plugins/common/src/modules/hoc/with-store.js
  plugins/common/src/modules/store/configure-store.js
  plugins/common/src/modules/store/index.js
  plugins/events/src/modules/blocks/event-website/style.pcss
  plugins/events/src/modules/blocks/event-website/template.js
  plugins/events/src/modules/editor/style.pcss
  plugins/events/src/modules/editor/utils/range.js
  plugins/events/src/modules/elements/search-or-create/style.pcss
Labels: status:code-review

#305 Feature/112921 advanced options
  package-lock.json
  package.json
  plugins/common/src/modules/elements/accordion/AccordionRow.js
  plugins/common/src/modules/elements/accordion/__tests__/AccordionRow.test.js
  plugins/common/src/modules/elements/accordion/__tests__/__snapshots__/AccordionRow.test.js.snap
  plugins/common/src/modules/elements/accordion/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/accordion/__tests__/element.test.js
  plugins/common/src/modules/elements/accordion/element.js
  plugins/common/src/modules/elements/accordion/style.pcss
  plugins/common/src/modules/elements/button/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/button/__tests__/element.test.js
  plugins/common/src/modules/elements/button/element.js
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/time-picker/element.js
  plugins/common/src/modules/elements/tooltip/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/tooltip/__tests__/element.test.js
  plugins/common/src/modules/elements/tooltip/element.js
  plugins/common/src/modules/utils/__tests__/slide.test.js
  plugins/common/src/modules/utils/__tests__/time.test.js
  plugins/common/src/modules/utils/get-hidden-height.js
  plugins/common/src/modules/utils/index.js
  plugins/common/src/modules/utils/slide.js
  plugins/common/src/modules/utils/time.js
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-label/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-label/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-picker/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-picker/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-picker/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration/template.js
  plugins/tickets/src/modules/elements/date-time-range-picker/element.js
  plugins/tickets/src/modules/elements/date-time-range-picker/style.pcss
  plugins/tickets/src/modules/elements/index.js
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/element.test.js
  plugins/tickets/src/modules/elements/label-with-tooltip/element.js
  plugins/tickets/src/modules/elements/label-with-tooltip/style.pcss
Labels: review:merge

#312 Fix failing tests
  lerna.json
  plugins/common/src/modules/hoc/__tests__/__snapshots__/with-store.test.js.snap
  plugins/common/src/modules/hoc/__tests__/with-store.test.js
  plugins/events/src/modules/editor/utils/range.js
Labels: review:merge

#313 Prevent Gcal from infinite looping on the Administration
  plugins/events/src/Tribe/Blocks/Event_Links.php
  plugins/events/src/Tribe/Compatibility/Tickets.php
Labels: review:merge

#314 Make sure Frontend elements load the CSS properly
  plugins/common/src/Tribe/Editor.php
  plugins/events/src/Tribe/Blocks/Abstract.php
  plugins/events/src/Tribe/Blocks/Classic_Event_Details.php
  plugins/events/src/Tribe/Blocks/Event_Category.php
  plugins/events/src/Tribe/Blocks/Event_Datetime.php
  plugins/events/src/Tribe/Blocks/Event_Links.php
  plugins/events/src/Tribe/Blocks/Event_Organizer.php
  plugins/events/src/Tribe/Blocks/Event_Price.php
  plugins/events/src/Tribe/Blocks/Event_Tags.php
  plugins/events/src/Tribe/Blocks/Event_Venue.php
  plugins/events/src/Tribe/Blocks/Event_Website.php
  plugins/events/src/Tribe/Blocks/Featured_Image.php
  plugins/events/src/Tribe/Editor.php
  plugins/events/src/Tribe/Meta.php
  plugins/events/src/Tribe/Provider.php
  plugins/events/src/styles/classic-event-details/backend.js
  plugins/events/src/styles/classic-event-details/backend.pcss
  plugins/events/src/styles/classic-event-details/style.pcss
  plugins/events/src/styles/event-category/frontend.js
  plugins/events/src/styles/event-category/frontend.pcss
  plugins/events/src/styles/event-datetime/frontend.js
  plugins/events/src/styles/event-datetime/frontend.pcss
  plugins/events/src/styles/event-links/frontend.js
  plugins/events/src/styles/event-links/frontend.pcss
  plugins/events/src/styles/event-organizer/frontend.js
  plugins/events/src/styles/event-organizer/frontend.pcss
  plugins/events/src/styles/event-price/frontend.js
  plugins/events/src/styles/event-price/frontend.pcss
  plugins/events/src/styles/event-tags/frontend.js
  plugins/events/src/styles/event-tags/frontend.pcss
  plugins/events/src/styles/event-venue/frontend.js
  plugins/events/src/styles/event-venue/frontend.pcss
  plugins/events/src/styles/event-website/frontend.js
  plugins/events/src/styles/event-website/frontend.pcss
  plugins/events/src/styles/index.js
Labels: review:merge

#310 Add <Ticket> block
  .eslintrc
  plugins/common/src/modules/utils/__tests__/number.test.js
  plugins/common/src/modules/utils/__tests__/proptypes.test.js
  plugins/common/src/modules/utils/index.js
  plugins/common/src/modules/utils/number.js
  plugins/common/src/modules/utils/proptypes.js
  plugins/tickets/src/modules/blocks/ticket/Container.js
  plugins/tickets/src/modules/blocks/ticket/Template.js
  plugins/tickets/src/modules/blocks/ticket/style.pcss
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/elements/index.js
  plugins/tickets/src/modules/elements/quantity-bar/__tests__/__snapshots__/bar.test.js.snap
  plugins/tickets/src/modules/elements/quantity-bar/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/quantity-bar/__tests__/bar.test.js
  plugins/tickets/src/modules/elements/quantity-bar/__tests__/element.test.js
  plugins/tickets/src/modules/elements/quantity-bar/bar.js
  plugins/tickets/src/modules/elements/quantity-bar/element.js
  plugins/tickets/src/modules/elements/quantity-bar/style.pcss
  plugins/tickets/src/modules/elements/ticket-status/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/ticket-status/__tests__/element.test.js
  plugins/tickets/src/modules/elements/ticket-status/element.js
Labels: status:code-review

#324 Prevent generation of empty classic blocks
  plugins/events/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#317 Feature/112920 rsvp container
  plugins/common/src/modules/elements/button/element.js
  plugins/common/src/modules/elements/checkbox/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/checkbox/__tests__/element.test.js
  plugins/common/src/modules/elements/checkbox/element.js
  plugins/common/src/modules/elements/checkbox/style.pcss
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/tooltip/element.js
  plugins/events/src/modules/elements/checkbox/element.js
  plugins/events/src/modules/elements/checkbox/style.pcss
  plugins/events/src/modules/elements/index.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-action-buttons/attendees-action-button/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-action-buttons/index.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-action-buttons/settings-action-button/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-content/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-content/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-content/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-header/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-header/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-header/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/template.js
  plugins/tickets/src/modules/elements/action-button/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/action-button/element.js
  plugins/tickets/src/modules/elements/action-button/style.pcss
  plugins/tickets/src/modules/elements/action-dashboard/element.js
  plugins/tickets/src/modules/elements/action-dashboard/style.pcss
  plugins/tickets/src/modules/elements/container-panel/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/container-panel/__tests__/element.test.js
  plugins/tickets/src/modules/elements/container-panel/element.js
  plugins/tickets/src/modules/elements/container-panel/style.pcss
  plugins/tickets/src/modules/elements/index.js
  plugins/tickets/src/modules/elements/numeric-label/element.js
Labels: review:merge

#323 Allow for saving on new event creation
  plugins/common/src/modules/hoc/with-save-data.js
  readme.md
Labels: review:merge

#318 Feature/112956 rsvp inactive state
  plugins/tickets/src/modules/blocks/rsvp/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/template.js
  plugins/tickets/src/modules/blocks/tickets/Template.js
  plugins/tickets/src/modules/elements/container-panel/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/container-panel/element.js
  plugins/tickets/src/modules/elements/disabled-tickets/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/disabled-tickets/__tests__/element.test.js
  plugins/tickets/src/modules/elements/disabled-tickets/element.js
  plugins/tickets/src/modules/elements/disabled-tickets/style.pcss
  plugins/tickets/src/modules/elements/inactive-block/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/inactive-block/__tests__/element.test.js
  plugins/tickets/src/modules/elements/inactive-block/element.js
  plugins/tickets/src/modules/elements/inactive-block/style.pcss
  plugins/tickets/src/modules/elements/index.js
Labels: status:code-review

#319 Add form to create a new ticket
  __mocks__/@wordpress/components.js
  __mocks__/uniqid.js
  package-lock.json
  plugins/common/src/modules/elements/accordion/AccordionRow/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/template.js
  plugins/tickets/src/modules/blocks/tickets/Container.js
  plugins/tickets/src/modules/blocks/tickets/Template.js
  plugins/tickets/src/modules/blocks/tickets/settings/template.js
  plugins/tickets/src/modules/elements/capacity-table/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/capacity-table/element.js
  plugins/tickets/src/modules/elements/index.js
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/element.test.js
  plugins/tickets/src/modules/elements/label-with-tooltip/element.js
  plugins/tickets/src/modules/elements/ticket-form/advanced-options/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/advanced-options/__tests__/template.test.js
  plugins/tickets/src/modules/elements/ticket-form/advanced-options/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/advanced-options/template.js
  plugins/tickets/src/modules/elements/ticket-form/attendees-registration/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/attendees-registration/template.js
  plugins/tickets/src/modules/elements/ticket-form/capacity/template.js
  plugins/tickets/src/modules/elements/ticket-form/duration/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/duration/__tests__/template.test.js
  plugins/tickets/src/modules/elements/ticket-form/duration/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/duration/template.js
  plugins/tickets/src/modules/elements/ticket-form/element.js
  plugins/tickets/src/modules/elements/ticket-form/footer/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/footer/template.js
  plugins/tickets/src/modules/elements/ticket-form/header/__tests__/__snapshots__/template.tests.js.snap
  plugins/tickets/src/modules/elements/ticket-form/header/__tests__/template.tests.js
  plugins/tickets/src/modules/elements/ticket-form/header/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/header/template.js
  plugins/tickets/src/modules/elements/ticket-form/sku/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/sku/__tests__/template.test.js
  plugins/tickets/src/modules/elements/ticket-form/sku/template.js
  plugins/tickets/src/modules/elements/ticket-form/style.pcss
Labels: review:merge

#325 Fix/114451 container panel element fix
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container/template.js
  plugins/tickets/src/modules/elements/container-panel/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/container-panel/__tests__/element.test.js
  plugins/tickets/src/modules/elements/container-panel/element.js
  plugins/tickets/src/modules/elements/container-panel/style.pcss
Labels: review:merge

#321 Feature/112947 going not going counters
  plugins/common/src/modules/elements/counter/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/counter/__tests__/element.test.js
  plugins/common/src/modules/elements/counter/element.js
  plugins/common/src/modules/elements/counter/style.pcss
  plugins/common/src/modules/elements/index.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-header/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-header/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-counters/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-counters/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-counters/template.js
Labels: review:merge

#327 Render the google map in the event venue block.
  plugins/events/src/modules/blocks/event-venue/template.js
  plugins/events/src/modules/elements/google-map/element.js
  readme.md
Labels: review:enhance

#329 Add TODO anotation to keep track of central question
  plugins/events/src/modules/blocks/event-organizer/template.js
Labels: status:code-review

#330 Load assets in the correct priority Common > Events > Tickets
  events-gutenberg.php
  plugins/common/src/Tribe/Assets.php
  plugins/tickets/src/Tribe/Assets.php
Labels: review:merge, status:code-review

#322 Feature/112925 attendee registration
  __mocks__/@wordpress/components.js
  plugins/common/src/modules/data/reducers/index.js
  plugins/common/src/modules/data/reducers/ui/__tests__/__snapshots__/actions.test.js.snap
  plugins/common/src/modules/data/reducers/ui/__tests__/__snapshots__/selectors.test.js.snap
  plugins/common/src/modules/data/reducers/ui/__tests__/actions.test.js
  plugins/common/src/modules/data/reducers/ui/__tests__/selectors.test.js
  plugins/common/src/modules/data/reducers/ui/__tests__/types.test.js
  plugins/common/src/modules/data/reducers/ui/actions.js
  plugins/common/src/modules/data/reducers/ui/index.js
  plugins/common/src/modules/data/reducers/ui/reducer.js
  plugins/common/src/modules/data/reducers/ui/reducers/__tests__/__snapshots__/accordion.test.js.snap
  plugins/common/src/modules/data/reducers/ui/reducers/__tests__/accordion.test.js
  plugins/common/src/modules/data/reducers/ui/reducers/accordion.js
  plugins/common/src/modules/data/reducers/ui/reducers/index.js
  plugins/common/src/modules/data/reducers/ui/selectors.js
  plugins/common/src/modules/data/reducers/ui/types.js
  plugins/common/src/modules/elements/accordion/AccordionRow/__tests__/__snapshots__/template.test.js.snap
  plugins/common/src/modules/elements/accordion/AccordionRow/__tests__/template.test.js
  plugins/common/src/modules/elements/accordion/AccordionRow/container.js
  plugins/common/src/modules/elements/accordion/AccordionRow/template.js
  plugins/common/src/modules/elements/accordion/element.js
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/label-with-modal/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/label-with-modal/__tests__/element.test.js
  plugins/common/src/modules/elements/label-with-modal/element.js
  plugins/common/src/modules/elements/label-with-modal/style.pcss
  plugins/common/src/modules/elements/labeled-item/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/labeled-item/__tests__/element.test.js
  plugins/common/src/modules/elements/labeled-item/element.js
  plugins/common/src/modules/elements/modal-button/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/modal-button/__tests__/element.test.js
  plugins/common/src/modules/elements/modal-button/element.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-advanced-options/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-attendee-registration/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/rsvp-attendee-registration/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-container-content/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-duration-label/style.pcss
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/label-with-tooltip/__tests__/element.test.js
  plugins/tickets/src/modules/elements/label-with-tooltip/element.js
  plugins/tickets/src/modules/elements/label-with-tooltip/style.pcss
  plugins/tickets/src/modules/elements/ticket-form/advanced-options/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/capacity/template.js
  plugins/tickets/src/modules/elements/ticket-form/duration/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/sku/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/ticket-form/sku/template.js
Labels: review:merge

#326 Feature/112936 header image upload
  package-lock.json
  plugins/common/src/modules/elements/image-upload/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/image-upload/__tests__/element.test.js
  plugins/common/src/modules/elements/image-upload/element.js
  plugins/common/src/modules/elements/image-upload/style.pcss
  plugins/common/src/modules/elements/image/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/image/__tests__/element.test.js
  plugins/common/src/modules/elements/image/element.js
  plugins/common/src/modules/elements/index.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-header-image/container.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-header-image/template.js
  plugins/tickets/src/modules/blocks/rsvp/rsvp-settings-dashboard/template.js
  plugins/tickets/src/modules/blocks/tickets/Template.js
  plugins/tickets/src/modules/data/blocks/index.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/reducer.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/actions.js
  plugins/tickets/src/modules/data/blocks/rsvp/index.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducer.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/header-image.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/header-image.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/header-image.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/data/blocks/rsvp/types.js
  plugins/tickets/src/modules/data/blocks/sagas.js
Labels: review:merge

#332 RSVP: Use the `post_id` from the main template
  plugins/tickets/src/Tribe/Blocks/Rsvp.php
Labels: review:merge

#333 Fix/113527 timezone display issue
  plugins/events/src/modules/blocks/event-datetime/container.js
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/editor/utils/__tests__/date.test.js
  plugins/events/src/modules/editor/utils/date.js
  readme.md
Labels: review:merge

#335 Fields for RSVP base fields
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/Tribe/Provider.php
Labels: review:merge
