Repository moderntribe/events-gutenberg, pull requests merged in 2018-11, with the labels that each got.

#448 Update initial ticket state to match event date and time
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  readme.md
Labels: review:merge

#450 Sync with latest from master
  plugins/common/src/modules/elements/block-icon/style.pcss
  plugins/events/src/modules/blocks/classic-event-details/index.js
  plugins/events/src/modules/blocks/event-category/index.js
  plugins/events/src/modules/blocks/event-datetime/index.js
  plugins/events/src/modules/blocks/event-links/index.js
  plugins/events/src/modules/blocks/event-organizer/index.js
  plugins/events/src/modules/blocks/event-price/index.js
  plugins/events/src/modules/blocks/event-tags/index.js
  plugins/events/src/modules/blocks/event-venue/index.js
  plugins/events/src/modules/blocks/event-website/index.js
  plugins/events/src/modules/blocks/featured-image/index.js
  plugins/events/src/modules/icons/categories.svg
  plugins/events/src/modules/icons/classic.svg
  plugins/events/src/modules/icons/date-time.svg
  plugins/events/src/modules/icons/featured-image.svg
  plugins/events/src/modules/icons/index.js
  plugins/events/src/modules/icons/organizer.svg
  plugins/events/src/modules/icons/price.svg
  plugins/events/src/modules/icons/sharing.svg
  plugins/events/src/modules/icons/tags.svg
  plugins/events/src/modules/icons/venue.svg
  plugins/events/src/modules/icons/website.svg
  plugins/tickets/src/modules/blocks/attendees/index.js
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/action-buttons/attendees-action-button/template.js
  plugins/tickets/src/modules/blocks/rsvp/container-content/template.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/rsvp/template.js
  plugins/tickets/src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/index.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/orders/template.js
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/actions.js
  plugins/tickets/src/modules/data/blocks/rsvp/sagas.js
  plugins/tickets/src/modules/data/blocks/rsvp/types.js
  plugins/tickets/src/modules/icons/attendees.svg
  plugins/tickets/src/modules/icons/index.js
  plugins/tickets/src/modules/icons/orders.svg
  plugins/tickets/src/modules/icons/rsvp.svg
  plugins/tickets/src/modules/icons/tickets.svg
  readme.md
Labels: review:merge

#452 quick fix for undefined wp object error
  plugins/common/src/Tribe/Assets.php
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Assets.php
  readme.md
Labels: review:merge

#451 Fix/115804 capacity ui
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/capacity/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/capacity/template.js
  plugins/tickets/src/modules/blocks/tickets/capacity-table/container.js
  plugins/tickets/src/modules/blocks/tickets/capacity-table/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ui.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/ui.test.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/index.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/__tests__/__snapshots__/settings.spec.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/__tests__/__snapshots__/tmp.spec.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/__tests__/settings.spec.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/__tests__/tmp.spec.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/index.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/settings/tmp.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ticket.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ui.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  readme.md
Labels: review:merge

#455 Feature/117488 single recurrence multi day
  plugins/events-pro/src/modules/elements/recurring-field/singular.js
Labels: review:merge

#459 Prevent updates of attributes with same data
  plugins/events-pro/src/modules/blocks/recurrence-exception/index.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/index.js
  plugins/events-pro/src/modules/blocks/recurrence/template.js
  plugins/events-pro/src/modules/data/shared/sync.js
  plugins/events-pro/src/modules/elements/attribute-sync/element.js
Labels: review:merge

#449 Update additional fields default settings
  package-lock.json
  plugins/events-pro/src/Tribe/Additional_Fields.php
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/admin-view/custom-fields/gutenberg.php
  plugins/events-pro/src/modules/admin-additional-fields/index.js
  readme.md
Labels: review:merge

#453 add attendee info as a metabox
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/label-with-link/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/label-with-link/__tests__/element.test.js
  plugins/common/src/modules/elements/label-with-link/element.js
  plugins/common/src/modules/elements/label-with-link/style.pcss
  plugins/common/src/modules/elements/label-with-modal/element.js
  plugins/common/src/modules/elements/link/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/link/__tests__/element.test.js
  plugins/common/src/modules/elements/link/element.js
  plugins/common/src/modules/elements/modal-button/element.js
  plugins/tickets/src/Tribe/Assets.php
  plugins/tickets/src/Tribe/Attendee_Registration.php
  plugins/tickets/src/Tribe/Provider.php
  plugins/tickets/src/modules/blocks/rsvp/action-buttons/attendees-action-button/container.js
  plugins/tickets/src/modules/blocks/rsvp/action-buttons/attendees-action-button/template.js
  plugins/tickets/src/modules/blocks/rsvp/action-dashboard/container.js
  plugins/tickets/src/modules/blocks/rsvp/attendee-registration/container.js
  plugins/tickets/src/modules/blocks/rsvp/attendee-registration/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/attendee-registration/template.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/attendees-registration/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/attendees-registration/style.pcss
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/attendees-registration/template.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/orders/template.js
  plugins/tickets/src/modules/blocks/tickets/action-dashboard/template.js
  plugins/tickets/src/modules/data/blocks/rsvp/thunks.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/ticket/actions.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/ticket.test.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/elements/action-button/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/action-button/__tests__/element.test.js
  plugins/tickets/src/modules/elements/action-button/element.js
  plugins/tickets/src/modules/elements/action-button/style.pcss
  plugins/tickets/src/modules/elements/container-panel/style.pcss
Labels: review:merge

#457 use babel-runtime instead of @babel/runtime
  package-lock.json
  package.json
Labels: review:merge

#458 fixing some minor text/translation issues
  plugins/common/src/Tribe/Assets.php
  plugins/events/src/Tribe/Meta.php
  plugins/events/src/Tribe/Plugin.php
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/blocks/event-organizer/details/form.js
  plugins/events/src/modules/blocks/event-organizer/template.js
  plugins/events/src/modules/blocks/event-venue/template.js
  plugins/events/src/modules/blocks/featured-image/block.js
  plugins/events/src/modules/elements/upsell/element.js
  plugins/tickets/src/modules/blocks/rsvp/container-header/template.js
  plugins/tickets/src/modules/blocks/rsvp/duration-label/template.js
  plugins/tickets/src/modules/blocks/rsvp/template.js
  plugins/tickets/src/modules/blocks/tickets/availability/element.js
  plugins/tickets/src/modules/blocks/tickets/template.js
Labels: review:merge

#465 Update tickets to show login prompt when login is required to purchas…
  plugins/tickets/src/views/blocks/tickets.php
  plugins/tickets/src/views/blocks/tickets/submit-button.php
  plugins/tickets/src/views/blocks/tickets/submit-login.php
  plugins/tickets/src/views/blocks/tickets/submit.php
Labels: review:merge

#434 Feature/116989 app subdirectory
  package-lock.json
  package.json
  plugins/common/src/Tribe/Assets.php
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events/src/Tribe/Assets.php
  plugins/events/src/Tribe/Blocks/Classic_Event_Details.php
  plugins/events/src/Tribe/Blocks/Event_Category.php
  plugins/events/src/Tribe/Blocks/Event_Datetime.php
  plugins/events/src/Tribe/Blocks/Event_Links.php
  plugins/events/src/Tribe/Blocks/Event_Organizer.php
  plugins/events/src/Tribe/Blocks/Event_Price.php
  plugins/events/src/Tribe/Blocks/Event_Tags.php
  plugins/events/src/Tribe/Blocks/Event_Venue.php
  plugins/events/src/Tribe/Blocks/Event_Website.php
  plugins/events/src/Tribe/Blocks/Featured_Image.php
  plugins/events/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Assets.php
  plugins/tickets/src/Tribe/Blocks/Attendees.php
  plugins/tickets/src/Tribe/Blocks/Rsvp.php
  plugins/tickets/src/Tribe/Blocks/Tickets.php
  webpack/common/webpack.config.js
  webpack/module/rules/styles.js
Labels: review:merge

#467 Add styles on the FE of the additinal fields
  plugins/events-pro/src/Tribe/Blocks/Additional_Field.php
  plugins/events-pro/src/styles/additional-fields/frontend.js
  plugins/events-pro/src/styles/additional-fields/frontend.pcss
Labels: review:merge

#470 Sync latest master into `task/additional-fields`
  package-lock.json
  package.json
  plugins/common/src/Tribe/Assets.php
  plugins/common/src/modules/data/reducers.js
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events/src/Tribe/Assets.php
  plugins/events/src/Tribe/Blocks/Classic_Event_Details.php
  plugins/events/src/Tribe/Blocks/Event_Category.php
  plugins/events/src/Tribe/Blocks/Event_Datetime.php
  plugins/events/src/Tribe/Blocks/Event_Links.php
  plugins/events/src/Tribe/Blocks/Event_Organizer.php
  plugins/events/src/Tribe/Blocks/Event_Price.php
  plugins/events/src/Tribe/Blocks/Event_Tags.php
  plugins/events/src/Tribe/Blocks/Event_Venue.php
  plugins/events/src/Tribe/Blocks/Event_Website.php
  plugins/events/src/Tribe/Blocks/Featured_Image.php
  plugins/events/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Assets.php
  plugins/tickets/src/Tribe/Blocks/Attendees.php
  plugins/tickets/src/Tribe/Blocks/Rsvp.php
  plugins/tickets/src/Tribe/Blocks/Tickets.php
  plugins/tickets/src/views/blocks/tickets.php
  plugins/tickets/src/views/blocks/tickets/submit-button.php
  plugins/tickets/src/views/blocks/tickets/submit-login.php
  plugins/tickets/src/views/blocks/tickets/submit.php
  webpack/common/webpack.config.js
  webpack/module/rules/styles.js
Labels: review:merge

#456 Add in /tickets links for RSVPs and tickets
  plugins/tickets/src/views/blocks/attendees/order-links.php
  plugins/tickets/src/views/blocks/rsvp.php
  plugins/tickets/src/views/blocks/tickets.php
Labels: review:merge

#466 Fix/117048 rsvp unlimited capacity
  plugins/tickets/src/modules/blocks/rsvp/container-header/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/container-header/template.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/elements/numeric-label/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/numeric-label/__tests__/element.test.js
  plugins/tickets/src/modules/elements/numeric-label/element.js
  plugins/tickets/src/views/blocks/rsvp/details/availability.php
Labels: review:merge

#462 Fix/117421 cannot select start times
  plugins/common/src/modules/data/reducers.js
  plugins/events-pro/src/modules/data/shared/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/shared/sagas.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/template.js
Labels: review:merge

#473 Feature/common externals
  package-lock.json
  package.json
  plugins/common/src/Tribe/Assets.php
  plugins/common/src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
  plugins/common/webpack.config.js
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events/src/Tribe/Editor.php
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/tickets/src/Tribe/Assets.php
  webpack/common/webpack.config.js
  webpack/externals/index.js
  webpack/externals/tribe/common.js
  webpack/externals/vendor.js
Labels: status:code-review

#474 Prevent Notice from Index not set
  plugins/events-pro/src/Tribe/Additional_Fields.php
Labels: review:merge

#475 add conditional to update natural language label in saga
  plugins/events/src/modules/data/blocks/datetime/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/datetime/sagas.js
Labels: status:code-review

#478 add changelog for redux infinite loop fix
  readme.md
Labels: review:merge

#479 Migrate Classic recurrence into Blocks
  plugins/events/src/Tribe/Editor.php
Labels: review:changelog, review:merge

#460 Convert Block data into Classic recurrence meta data
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Recurrence/Blocks.php
  plugins/events-pro/src/Tribe/Recurrence/Classic.php
  plugins/events-pro/src/Tribe/Recurrence/Parser_Interface.php
  plugins/events-pro/src/Tribe/Recurrence/Provider.php
  plugins/tickets/src/Tribe/REST/Compatibility.php
Labels: review:merge

#480 Fix the usage of a wrong named variable
  plugins/events/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#477 Include Theme lookup for front-end facing Templates
  plugins/events-pro/src/Tribe/Template/Admin.php
  plugins/events-pro/src/Tribe/Template/Frontend.php
  plugins/events/src/Tribe/Template.php
  readme.md
Labels: review:merge

#481 Fix/rsvp capacity display
  plugins/tickets/src/modules/blocks/rsvp/container-header/container.js
  plugins/tickets/src/modules/blocks/rsvp/container-header/template.js
  readme.md
Labels: review:merge

#482 Fix/tribe js config
  plugins/common/src/Tribe/Assets.php
  plugins/events/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#485 Fix/117035 timezone issue
  plugins/common/src/modules/utils/date.js
  plugins/common/src/modules/utils/globals.js
  plugins/common/src/modules/utils/timezone.js
  plugins/events/src/modules/blocks/event-category/block.js
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/datetime/reducer.js
  plugins/events/src/modules/data/blocks/datetime/sagas.js
  plugins/events/src/modules/data/blocks/price/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/price/reducer.js
  plugins/events/src/modules/data/blocks/price/sagas.js
  plugins/events/src/modules/editor/__tests__/settings.test.js
  plugins/events/src/modules/editor/index.js
  plugins/events/src/modules/editor/settings.js
  readme.md
Labels: review:changelog, status:code-review

#483 add rsvp and attendees blocks to template for classic editor
  plugins/tickets/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#484 Add Queue status `admin_ajax` response
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Recurrence/Queue_Status.php
Labels: review:merge

#487 Feature/117770 block ui editing
  plugins/events-pro/src/modules/data/index.js
  plugins/events-pro/src/modules/data/reducers.js
  plugins/events-pro/src/modules/data/sagas.js
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/actions.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/reducer.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/sagas.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/types.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/actions.spec.js
  plugins/events-pro/src/modules/data/status/__tests__/reducer.spec.js
  plugins/events-pro/src/modules/data/status/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/status/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/status/__tests__/types.spec.js
  plugins/events-pro/src/modules/data/status/actions.js
  plugins/events-pro/src/modules/data/status/index.js
  plugins/events-pro/src/modules/data/status/reducer.js
  plugins/events-pro/src/modules/data/status/sagas.js
  plugins/events-pro/src/modules/data/status/selectors.js
  plugins/events-pro/src/modules/data/status/types.js
  plugins/events-pro/src/modules/data/ui/types.js
  plugins/events/src/modules/blocks/event-datetime/container.js
  plugins/events/src/modules/blocks/event-datetime/style.pcss
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/__snapshots__/actions.test.js.snap
  plugins/events/src/modules/data/blocks/datetime/__tests__/__snapshots__/reducers.test.js.snap
  plugins/events/src/modules/data/blocks/datetime/__tests__/actions.test.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/reducers.test.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/selectors.test.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/types.js
  plugins/events/src/modules/data/blocks/datetime/actions.js
  plugins/events/src/modules/data/blocks/datetime/reducer.js
  plugins/events/src/modules/data/blocks/datetime/sagas.js
  plugins/events/src/modules/data/blocks/datetime/selectors.js
  plugins/events/src/modules/data/blocks/datetime/types.js
Labels: review:merge

#490 fix fatal error for interface
  plugins/common/src/Tribe/Blocks/Interface.php
Labels: review:merge

#492 :bookmark: Update to hide all day option
  plugins/events-pro/src/modules/elements/from-time-range-picker/template.js
Labels: review:merge

#491 Add in series editing success notice
  plugins/events-pro/src/modules/data/status/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/status/sagas.js
Labels: review:merge

#488 Convert numbers into strings for Classic Recurrence
  plugins/events-pro/src/Tribe/Recurrence/Classic.php
Labels: review:merge

#494 fix/117840 date time block display
  plugins/common/src/Tribe/Assets.php
  plugins/events/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#495 Fix/common events dependencies
  package-lock.json
  package.json
  plugins/common/src/modules/data/editor/post-types.js
  plugins/common/src/modules/data/forms/__tests__/__snapshots__/actions.test.js.snap
  plugins/common/src/modules/data/forms/__tests__/types.js
  plugins/common/src/modules/data/forms/reducers/form.js
  plugins/common/src/modules/data/forms/types.js
  plugins/common/src/modules/hoc/__tests__/__snapshots__/with-form.test.js.snap
  plugins/events/src/modules/blocks/classic-event-details/event-details-organizers/template.js
  plugins/events/src/modules/blocks/event-organizer/container.js
  plugins/events/src/modules/blocks/event-venue/container.js
  plugins/events/src/modules/blocks/event-venue/template.js
  plugins/events/src/modules/data/details/reducers/details.js
  plugins/events/src/modules/data/search/reducers/search.js
  plugins/events/src/modules/editor/__tests__/post-types.test.js
Labels: review:merge

#496 Fix/117016 attendees and orders icons
  plugins/tickets/src/modules/blocks/rsvp/action-buttons/attendees-action-button/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/orders/template.js
  plugins/tickets/src/modules/elements/action-button/style.pcss
  readme.md
Labels: review:merge

#497 Fix/117036 tickets block sidebar
  plugins/tickets/src/modules/blocks/tickets/controls/container.js
  plugins/tickets/src/modules/blocks/tickets/controls/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  readme.md
Labels: status:code-review

#489 Remove recurrence keys if `_EventRecurrence` is deleted
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Recurrence/Blocks_Meta.php
  plugins/events-pro/src/Tribe/Recurrence/Provider.php
Labels: review:merge

#498 Move the action to trigger recurrence rules
  plugins/events-pro/src/Tribe/Recurrence/Provider.php
Labels: review:merge

#499 Add number of items created and date of the last one
  plugins/events-pro/src/Tribe/Recurrence/Queue_Status.php
Labels: review:merge

#493 Fix/block fe display issues
  plugins/events/src/Tribe/Template/Overwrite.php
  plugins/events/src/views/blocks/event-datetime.php
  plugins/events/src/views/blocks/event-links.php
  plugins/events/src/views/blocks/event-price.php
  plugins/events/src/views/blocks/event-website.php
  readme.md
Labels: review:merge

#500 Is classic editor if forced by plugin "Classic Editor"
  plugins/common/src/Tribe/Plugin.php
  plugins/events-pro/src/Tribe/Meta.php
Labels: review:merge

#503 Notification/events created
  __mocks__/@wordpress/i18n.js
  plugins/events-pro/src/modules/data/status/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/status/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/status/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/status/sagas.js
  plugins/events-pro/src/modules/data/status/selectors.js
Labels: review:merge

#501 Fix/117850 ticket blocks sales progress
  plugins/tickets/src/modules/blocks/ticket/display-container/display/container.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/__snapshots__/bar.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/bar.test.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/element.test.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/bar.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/element.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/style.pcss
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/capacity/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/capacity/template.js
  plugins/tickets/src/modules/blocks/tickets/capacity-table/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/capacity-table/__tests__/template.test.js
  plugins/tickets/src/modules/blocks/tickets/capacity-table/container.js
  plugins/tickets/src/modules/blocks/tickets/capacity-table/template.js
  plugins/tickets/src/modules/blocks/tickets/container/container.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  readme.md
Labels: review:merge

#506 Add attendee opt-out option for RSVPs
  plugins/tickets/src/styles/rsvp/frontend.pcss
  plugins/tickets/src/views/blocks/rsvp/form/form.php
  plugins/tickets/src/views/blocks/rsvp/form/opt-out.php
  readme.md
Labels: review:merge

#505 Remove `data` script to be included on the page
  package-lock.json
  plugins/events/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Assets.php
  readme.md
Labels: review:merge

#509 Fix syntaxc error on PCSS file during build time
  package-lock.json
  plugins/tickets/src/styles/rsvp/frontend.pcss
Labels: review:merge

#510 Look for components.js in the App folder
  plugins/common/src/Tribe/Assets.php
Labels: status:code-review

#514 Fix/117465 weekday hover behavior
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/style.pcss
  readme.md
Labels: review:merge

#515 Opt-out option for tickets.
  plugins/tickets/src/resources/js/views/tickets.js
  plugins/tickets/src/styles/tickets/frontend.pcss
  plugins/tickets/src/views/blocks/tickets/content.php
  plugins/tickets/src/views/blocks/tickets/opt-out.php
  readme.md
Labels: review:merge

#512 Fix/112141 date time month picker issue
  plugins/events/src/modules/elements/month/element.js
  plugins/events/src/modules/elements/year-month-form/element.js
  readme.md
Labels: review:merge
