Repository moderntribe/events-gutenberg, pull requests merged in 2018-05, with the labels that each got.

#55 Add the time selection inside of the Dashboard component
  package-lock.json
  package.json
  readme.md
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-subtitle/style.pcss
  src/modules/editor/utils/dom.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/checkbox/style.pcss
  src/modules/elements/dashboard/element.js
  src/modules/elements/dashboard/style.pcss
  src/modules/elements/index.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/timezone-picker/element.js
  webpack.config.js
Labels: review:merge

#59 Add missing assets
  .gitignore
  src/resources/icons/checkbox-off.svg
  src/resources/icons/checkbox-on.svg
Labels: review:merge, status:code-review

#58 Apply linter rules on missing files
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-details/organizers.js
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-subtitle/index.js
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-venue/venue.js
  src/modules/editor/utils/date.js
  src/modules/editor/utils/geo-data.js
  src/modules/editor/utils/index.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/dashboard/element.js
  src/modules/elements/google-map/element.js
  src/modules/elements/index.js
  src/modules/elements/input/element.js
  src/modules/elements/meta-group/element.js
  src/modules/elements/organizer-form/element.js
  src/modules/elements/search-posts/element.js
  src/modules/elements/terms-list/element.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/timezone-picker/element.js
  src/modules/elements/venue-form/element.js
  src/modules/elements/venue-map/element.js
Labels: review:merge

#57 extract price into his own block from Event Details
  .eslintrc.json
  jest.config.json
  package.json
  readme.md
  src/Tribe/Blocks/Event_Price.php
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-price/style.pcss
  src/modules/blocks/index.js
  src/modules/editor/utils/range.js
  src/modules/editor/utils/tests/range.test.js
  src/modules/elements/dashboard/element.js
  src/views/blocks/event-details.php
  src/views/blocks/event-price.php
  src/views/blocks/parts/details.php
Labels: review:merge

#60 Add range logic for the Event Details
  jest.config.json
  package-lock.json
  package.json
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-subtitle/index.js
  src/modules/blocks/event-subtitle/style.pcss
  src/modules/editor/utils/date.js
  src/modules/editor/utils/dom.js
  src/modules/editor/utils/geo-data.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/range.js
  src/modules/editor/utils/tests/date.test.js
  src/modules/editor/utils/tests/moment.test.js
  src/modules/editor/utils/tests/range.test.js
  src/modules/editor/utils/tests/time.test.js
  src/modules/editor/utils/time.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/checkbox/style.pcss
  src/modules/elements/dashboard/element.js
  src/modules/elements/date-picker/element.js
  src/modules/elements/index.js
  src/modules/elements/month/element.js
  src/modules/elements/month/style.pcss
  src/modules/elements/time-picker/element.js
Labels: status:code-review

#61 Add store implementation for the Event Details
  .eslintrc.json
  jest.config.json
  jest.globals.js
  package.json
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-subtitle/index.js
  src/modules/blocks/index.js
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/data/organizers.js
  src/modules/data/venues.js
  src/modules/editor/utils/array.js
  src/modules/editor/utils/date.js
  src/modules/editor/utils/dom.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/object.js
  src/modules/editor/utils/string.js
  src/modules/editor/utils/tests/array.test.js
  src/modules/editor/utils/tests/object.test.js
  src/modules/editor/utils/tests/string.test.js
  src/modules/editor/utils/tests/time.test.js
  src/modules/editor/utils/time.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/month/element.js
  src/modules/elements/search-posts/element.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/timezone-picker/element.js
Labels: review:merge

#62 Make sure time selector listen for changes on the store
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/editor/utils/moment.js
Labels: review:merge

#63 Make sure date is set into the store
  src/modules/blocks/event-details/block.js
  src/modules/data/details/reducers.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/tests/moment.test.js
Labels: review:merge

#65 Move away from wp.blocks and use wp.editor to avoid warnings
  readme.md
  src/Tribe/Meta.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-venue/block.js
Labels: review:merge, status:code-review

#66 Prevent warning when using `moment` with no explicit format
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/data/details/reducers.js
  src/modules/editor/utils/date.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/tests/moment.test.js
  src/modules/elements/date-picker/element.js
Labels: review:merge, status:code-review

#68 Add Date and Time settings for event
  .eslintrc.json
  src/Tribe/Meta.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-subtitle/index.js
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/editor/utils/geo-data.js
  src/modules/editor/utils/object.js
  src/modules/editor/utils/tests/array.test.js
  src/modules/editor/utils/tests/object.test.js
  src/modules/editor/utils/tests/string.test.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/month/element.js
Labels: review:merge

#69 Add Tags and Categories blocks
  src/Tribe/Blocks/Event_Category.php
  src/Tribe/Blocks/Event_Tags.php
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/modules/blocks/event-category/block.js
  src/modules/blocks/event-category/index.js
  src/modules/blocks/event-category/style.pcss
  src/modules/blocks/event-tags/block.js
  src/modules/blocks/event-tags/index.js
  src/modules/blocks/event-tags/style.pcss
  src/modules/blocks/index.js
  src/modules/elements/terms-list/element.js
  src/views/blocks/event-category.php
  src/views/blocks/event-tags.php
Labels: review:merge, status:code-review

#71 Update changelog entry
  readme.md
Labels: review:merge

#70 When coming from classic editor, Event will keep it's classic blocks
  src/Tribe/Editor.php
Labels: review:merge, status:code-review

#73 Add Venue Block with support for search or create
  .eslintrc.json
  src/Tribe/Blocks/Abstract.php
  src/Tribe/Blocks/Event_Venue.php
  src/Tribe/Blocks/Interface.php
  src/Tribe/Editor.php
  src/Tribe/Meta.php
  src/Tribe/Provider.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-venue/style.pcss
  src/modules/blocks/event-venue/venue.js
  src/modules/blocks/style.pcss
  src/modules/data/details/reducers.js
  src/modules/data/venue/index.js
  src/modules/data/venue/reducer.js
  src/modules/data/venues.js
  src/modules/editor/settings.js
  src/modules/editor/utils/geo-data.js
  src/modules/editor/utils/globals.js
  src/modules/elements/google-map/element.js
  src/modules/elements/google-map/style.pcss
  src/modules/elements/index.js
  src/modules/elements/input/element.js
  src/modules/elements/organizer-form/element.js
  src/modules/elements/search-or-create/element.js
  src/modules/elements/search-or-create/style.pcss
  src/modules/elements/venue-form/element.js
  src/modules/elements/venue-form/style.pcss
  src/modules/elements/venue-map/element.js
Labels: review:merge

#72 Website block
  readme.md
  src/Tribe/Blocks/Event_Website.php
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/index.js
  src/modules/blocks/event-website/style.pcss
  src/modules/blocks/index.js
  src/modules/blocks/style.pcss
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
Labels: review:merge, status:code-review

#74 Organizer block
  src/Tribe/Blocks/Event_Organizer.php
  src/Tribe/Meta.php
  src/Tribe/Provider.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-details/index.js
  src/modules/blocks/event-details/organizers.js
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/details/form.js
  src/modules/blocks/event-organizer/details/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-organizer/style.pcss
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/index.js
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/data/organizers.js
  src/modules/data/organizers/block/index.js
  src/modules/data/organizers/block/reducers.js
  src/modules/data/venues.js
  src/modules/editor/utils/request.js
  src/modules/elements/organizer-form/utils.js
  src/modules/elements/search-or-create/element.js
  src/modules/elements/search-posts/element.js
  src/views/blocks/event-organizer.php
Labels: review:merge
