Repository moderntribe/events-gutenberg, pull requests merged in 2018-06, with the labels that each got.

#75 Rename classnames for the blocks
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/classic-event-details/organizers.js
  src/modules/blocks/event-category/block.js
  src/modules/blocks/event-category/style.pcss
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-datetime/style.pcss
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/details/form.js
  src/modules/blocks/event-organizer/details/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-organizer/style.pcss
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/style.pcss
  src/modules/blocks/event-tags/block.js
  src/modules/blocks/event-tags/style.pcss
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/style.pcss
  src/modules/blocks/event-venue/venue.js
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/style.pcss
  src/modules/blocks/style.pcss
  src/modules/editor/style.pcss
  src/modules/elements/checkbox/element.js
  src/modules/elements/checkbox/style.pcss
  src/modules/elements/dashboard/element.js
  src/modules/elements/dashboard/style.pcss
  src/modules/elements/date-picker/element.js
  src/modules/elements/date-picker/style.pcss
  src/modules/elements/google-map/element.js
  src/modules/elements/google-map/style.pcss
  src/modules/elements/input/element.js
  src/modules/elements/input/style.pcss
  src/modules/elements/meta-group/element.js
  src/modules/elements/month/style.pcss
  src/modules/elements/organizer-form/element.js
  src/modules/elements/search-or-create/element.js
  src/modules/elements/search-or-create/style.pcss
  src/modules/elements/search-posts/element.js
  src/modules/elements/search-posts/style.pcss
  src/modules/elements/terms-list/element.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/time-picker/style.pcss
  src/modules/elements/timezone-picker/style.pcss
  src/modules/elements/venue-form/element.js
  src/modules/elements/venue-form/style.pcss
Labels: review:merge

#76 Make sure classic editor opens Date Time dashboard
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/classic-event-details/organizers.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/style.pcss
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/data/organizers.js
  src/modules/data/organizers/block/index.js
  src/modules/data/organizers/block/reducers.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/object.js
  src/modules/editor/utils/tests/object.test.js
  src/modules/elements/dashboard/element.js
  src/modules/elements/search-posts/element.js
Labels: review:merge

#78 Apply HOC to favor updates into components
  package.json
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/data/venue/index.js
Labels: review:merge

#82 remove all day event toggle from sidebar
  src/modules/blocks/event-datetime/block.js
Labels: review:merge, status:code-review

#81 fix background color for multi day event
  src/modules/elements/month/style.pcss
Labels: review:merge, status:code-review

#79 Update SearchOrCreate component to use HOC
  src/Tribe/Blocks/Event_Venue.php
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/classic-event-details/organizers.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/index.js
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/data/organizers/index.js
  src/modules/data/organizers/reducers.js
  src/modules/data/search/organizers.js
  src/modules/data/search/venues.js
  src/modules/data/venue/index.js
  src/modules/elements/search-or-create/element.js
Labels: review:merge

#80 Simplest version of the Featured Image
  readme.md
  src/Tribe/Blocks/Featured_Image.php
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/modules/blocks/featured-image/block.js
  src/modules/blocks/featured-image/index.js
  src/modules/blocks/index.js
  src/views/blocks/featured-image.php
Labels: review:merge, status:code-review

#83 Update index.js
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/event-category/index.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-tags/index.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-website/index.js
  src/modules/blocks/featured-image/index.js
Labels: review:merge

#85 Remove boilerplate code for updates
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/index.js
  src/modules/data/details/index.js
  src/modules/data/details/reducers.js
  src/modules/editor/utils/moment.js
  src/modules/editor/utils/with-save-data.js
  src/modules/elements/dashboard/element.js
  src/resources/icons/link.svg
Labels: review:merge

#86 Refactor selectors to use TEC style
  src/modules/blocks/event-category/block.js
  src/modules/blocks/event-venue/block.js
  src/modules/data/details/index.js
  src/modules/data/organizers/index.js
  src/modules/data/venue/index.js
  src/modules/elements/dashboard/element.js
  src/modules/elements/meta-group/element.js
  src/modules/elements/terms-list/element.js
Labels: review:merge

#89 fix/107023 time separator all day
  src/modules/blocks/event-datetime/block.js
Labels: review:merge, status:code-review

#88 Fix/106585 year month nav
  src/modules/elements/index.js
  src/modules/elements/month/element.js
  src/modules/elements/month/style.pcss
  src/modules/elements/year-month-form/element.js
  src/modules/elements/year-month-form/style.pcss
Labels: review:merge

#90 fix/107268 tec blocks on pages and posts
  src/Tribe/Editor.php
Labels: review:merge

#93 Update placeholder label for event location to match spec
  src/modules/blocks/event-venue/block.js
Labels: review:merge

#92 Dont't close dashboard if sidebars are clicked
  src/modules/elements/dashboard/element.js
Labels: review:merge

#91 Updates in Organizers
  src/Tribe/Meta.php
  src/modules/blocks/classic-event-details/block.js
  src/modules/blocks/classic-event-details/organizer/actions.js
  src/modules/blocks/classic-event-details/organizer/index.js
  src/modules/blocks/classic-event-details/organizer/item.js
  src/modules/blocks/classic-event-details/organizer/name.js
  src/modules/blocks/classic-event-details/organizer/style.pcss
  src/modules/blocks/classic-event-details/organizers.js
  src/modules/blocks/event-datetime/block.js
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-website/block.js
  src/modules/blocks/style.pcss
  src/modules/data/details/reducers.js
  src/modules/data/organizers/index.js
  src/modules/data/organizers/reducers.js
  src/modules/data/search/venues.js
  src/modules/editor/hoc/with-request.js
  src/modules/editor/hoc/with-save-data.js
  src/modules/elements/index.js
  src/modules/elements/loading/index.js
  src/modules/elements/loading/style.pcss
  src/modules/elements/meta-group/element.js
  src/modules/elements/search-or-create/element.js
  src/modules/elements/search-posts/element.js
  src/modules/elements/search-posts/style.pcss
Labels: review:merge

#95 fix/108305 tags event categories block
  src/modules/blocks/event-category/block.js
  src/modules/blocks/event-category/style.pcss
  src/modules/blocks/event-tags/block.js
  src/modules/blocks/event-tags/style.pcss
  src/modules/blocks/style.pcss
  src/modules/elements/terms-list/element.js
  src/modules/elements/terms-list/style.pcss
Labels: review:merge, status:code-review

#94 Fix/108306 dashboard closing issue
  src/modules/elements/dashboard/element.js
Labels: review:merge, status:code-review

#96 Update PlainText elements into RichText where required
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-website/block.js
  src/modules/blocks/event-website/style.pcss
Labels: status:code-review

#103 Fix translation string
  readme.md
  src/modules/blocks/event-venue/block.js
Labels: review:merge

#105 Add autosave support for other post types
  readme.md
  src/Tribe/Blocks/Event_Datetime.php
  src/Tribe/Editor.php
Labels: review:merge

#104 Remove content from orgaanizer block template
  readme.md
  src/views/blocks/event-organizer.php
Labels: review:merge

#106 Apply feedback into the organizer and venue block
  readme.md
  src/Tribe/Meta.php
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-organizer/details/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/style.pcss
  src/modules/blocks/event-venue/venue.js
  src/modules/editor/utils/string.js
  src/modules/editor/utils/tests/string.test.js
  src/modules/elements/month/style.pcss
  src/modules/elements/search-or-create/style.pcss
  src/modules/elements/venue-form/style.pcss
  src/resources/icons/close.svg
  src/resources/icons/organizer.svg
  src/resources/icons/venue.svg
Labels: review:merge

#107 QA repairs for #103750
  readme.md
  src/modules/blocks/event-datetime/block.js
  src/modules/data/details/reducers.js
  src/modules/elements/dashboard/element.js
  src/modules/elements/month/element.js
Labels: review:merge

#110 Fix/108303 event sharing block issues
  readme.md
  src/Tribe/Editor.php
  src/modules/blocks/event-links/block.js
  src/modules/blocks/event-links/style.pcss
Labels: review:merge

#109 Fix/108535 delete block disconnect data
  readme.md
  src/modules/blocks/event-organizer/block.js
  src/modules/blocks/event-venue/block.js
  src/modules/data/organizers/reducers.js
Labels: review:merge

#108 Improve layout styles for block to avoid hide controls
  readme.md
  src/modules/editor/style.pcss
Labels: review:merge

#111 Enable selection of days in the past and add fitler for range days
  package.json
  readme.md
  src/modules/elements/month/element.js
Labels: review:merge

#114 remove removal of organizers on removal of block
  src/modules/blocks/event-organizer/block.js
Labels: review:merge, status:code-review

#113 Address feedback on blocks, input and icons
  readme.md
  src/modules/blocks/classic-event-details/index.js
  src/modules/blocks/event-category/index.js
  src/modules/blocks/event-datetime/index.js
  src/modules/blocks/event-links/index.js
  src/modules/blocks/event-organizer/details/style.pcss
  src/modules/blocks/event-organizer/index.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/event-price/style.pcss
  src/modules/blocks/event-tags/index.js
  src/modules/blocks/event-venue/index.js
  src/modules/blocks/event-website/index.js
  src/modules/blocks/featured-image/index.js
  src/modules/editor/style.pcss
  src/modules/elements/dashboard/style.pcss
  src/modules/elements/icons/element.js
  src/modules/elements/icons/style.pcss
  src/modules/elements/icons/tec.js
  src/modules/elements/index.js
  src/modules/elements/venue-form/style.pcss
  src/resources/icons/tec.svg
Labels: status:code-review

#117 Render Event links block based on their attributes
  readme.md
  src/views/blocks/event-links.php
Labels: review:merge

#118 Add FE for the event website
  readme.md
  src/Tribe/Template.php
  src/views/blocks/event-website.php
Labels: review:merge

#119 Remove boilerplate code in favor of attributes method
  src/views/blocks/event-links.php
Labels: review:merge

#115 Fix styles to follow styleguide
  readme.md
  src/modules/blocks/event-datetime/style.pcss
  src/modules/blocks/event-links/style.pcss
  src/modules/blocks/event-venue/style.pcss
  src/modules/blocks/event-venue/venue.js
  src/modules/elements/month/style.pcss
  src/modules/elements/organizer-form/element.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/time-picker/style.pcss
Labels: status:code-review

#120 Fix/108550 location block map
  readme.md
  src/modules/blocks/event-venue/style.pcss
  src/modules/elements/google-map/element.js
  src/modules/elements/google-map/style.pcss
Labels: review:merge

#121 Initial refactor of stores to use native Redux
  package.json
  src/modules/blocks/event-price/block.js
  src/modules/blocks/event-price/index.js
  src/modules/blocks/index.js
  src/modules/data/blocks/datetime/reducers.js
  src/modules/data/blocks/datetime/selectors.js
  src/modules/data/blocks/datetime/separators/reducers.js
  src/modules/data/blocks/datetime/separators/types.js
  src/modules/data/blocks/datetime/values/reducers.js
  src/modules/data/blocks/datetime/variants/reducers.js
  src/modules/data/blocks/middlewares/index.js
  src/modules/data/blocks/organizers/reducers.js
  src/modules/data/blocks/price/actions.js
  src/modules/data/blocks/price/reducers.js
  src/modules/data/blocks/price/selectors.js
  src/modules/data/blocks/price/types.js
  src/modules/data/blocks/reducers.js
  src/modules/data/blocks/selectors.js
  src/modules/data/blocks/venue/reducers.js
  src/modules/data/blocks/website/reducers.js
  src/modules/data/blocks/website/types.js
  src/modules/data/index.js
  src/modules/data/reducers.js
  src/modules/editor/hoc/with-save-data.js
  src/modules/editor/hoc/with-store.js
Labels: review:merge
