Repository moderntribe/events-gutenberg, pull requests merged in 2018-10, with the labels that each got.

#341 Register POST / DELETE / PUT methods on tickets endpoints
  events-gutenberg.php
  plugins/tickets/src/Tribe/REST/V1/Endpoints/Single_Ticket.php
  plugins/tickets/src/Tribe/REST/V1/Service_Provider.php
Labels: review:merge

#337 Buy tickets workflow for different providers.
  plugins/tickets/src/Tribe/Blocks/Tickets.php
  plugins/tickets/src/resources/js/views/tickets.js
  plugins/tickets/src/styles/tickets/frontend.pcss
  plugins/tickets/src/views/blocks/tickets.php
  plugins/tickets/src/views/blocks/tickets/button-submit.php
  plugins/tickets/src/views/blocks/tickets/commerce/fields-edd.php
  plugins/tickets/src/views/blocks/tickets/commerce/fields-tpp.php
  plugins/tickets/src/views/blocks/tickets/commerce/fields-woo.php
  plugins/tickets/src/views/blocks/tickets/commerce/fields.php
  plugins/tickets/src/views/blocks/tickets/extra-available-quantity.php
  plugins/tickets/src/views/blocks/tickets/extra-available-unlimited.php
  plugins/tickets/src/views/blocks/tickets/extra-available.php
  plugins/tickets/src/views/blocks/tickets/item.php
  plugins/tickets/src/views/blocks/tickets/quantity-number.php
Labels: review:merge

#338 Save the header and capacity attributes
  plugins/common/src/modules/utils/__tests__/api.js
  plugins/common/src/modules/utils/api.js
  plugins/tickets/src/modules/blocks/ticket/index.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/container.js
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/blocks/tickets/header-image/container.js
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  plugins/tickets/src/modules/blocks/tickets/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/ticket/actions.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ui.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/ui.test.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ui.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  plugins/tickets/src/modules/data/blocks/ticket/types.js
Labels: review:merge

#342 Load Meta fields into WP Endpoint for Going and Not Going Attendees
  plugins/tickets/src/Tribe/Meta.php
Labels: review:merge

#343 Feature/persist rsvp header image
  plugins/common/src/modules/elements/image-upload/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/image-upload/__tests__/element.test.js
  plugins/common/src/modules/elements/image-upload/element.js
  plugins/common/src/modules/elements/image-upload/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/header-image/container.js
  plugins/tickets/src/modules/blocks/rsvp/header-image/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/header-image/template.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/rsvp/settings-dashboard/container.js
  plugins/tickets/src/modules/blocks/rsvp/settings-dashboard/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/settings-dashboard/template.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/reducer.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/actions.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducer.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/details.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/temp-details.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/details.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/temp-details.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/details.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/temp-details.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/data/blocks/rsvp/thunks.js
  plugins/tickets/src/modules/data/blocks/rsvp/types.js
  plugins/tickets/src/modules/elements/settings-dashboard/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/settings-dashboard/__tests__/element.test.js
  plugins/tickets/src/modules/elements/settings-dashboard/element.js
  plugins/tickets/src/modules/elements/settings-dashboard/style.pcss
Labels: review:merge

#344 Feature/rsvp going not going react
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/counters/container.js
  plugins/tickets/src/modules/blocks/rsvp/duration-picker/container.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/data/__tests__/utils.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/reducer.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/actions.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducer.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/__tests__/temp-details.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/reducers/temp-details.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/data/blocks/rsvp/types.js
  plugins/tickets/src/modules/data/utils.js
Labels: status:code-review

#345 Add specificity without breaking required inputs.
  plugins/tickets/src/resources/js/views/tickets.js
Labels: review:merge, status:code-review

#340 ECP integration + Default values
  events-gutenberg.php
  plugins/common/src/modules/utils/globals.js
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events-pro/src/Tribe/Plugin.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events/src/modules/blocks/event-organizer/index.js
  plugins/events/src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
  plugins/events/src/modules/data/blocks/venue/reducer.js
  plugins/events/src/modules/data/blocks/venue/utils.js
  plugins/events/src/modules/editor/utils/geo-data.js
  plugins/events/src/modules/elements/venue-form/element.js
  readme.md
Labels: review:merge

#348 simplify select to get post id by removing HOC
  plugins/tickets/src/modules/blocks/rsvp/action-dashboard/container.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/header-image/container.js
Labels: review:merge

#351 Rename Tickets blocks
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/index.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/action-dashboard/container.js
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/blocks/tickets/index.js
Labels: status:code-review

#352 Add the `sold` property into the API
  plugins/tickets/src/Tribe/REST/V1/Service_Provider.php
  plugins/tickets/src/modules/blocks/ticket/display-container/display/container.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
  plugins/tickets/src/modules/blocks/tickets/action-dashboard/container.js
  plugins/tickets/src/modules/blocks/tickets/container/container.js
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/ticket/actions.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/ticket.test.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ticket.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/tickets.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  plugins/tickets/src/modules/data/blocks/ticket/types.js
Labels: review:merge

#353 Fix issues for ticket meta fields
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/__tests__/element.test.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/quantity-bar/element.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
Labels: review:merge

#355 Fix/ticket selector
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
Labels: review:merge

#349 Feature/113354 number input
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/input/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/elements/input/__tests__/element.test.js
  plugins/events-pro/src/modules/elements/input/element.js
  plugins/events-pro/src/modules/elements/input/style.pcss
  plugins/events-pro/src/modules/elements/number-input/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/elements/number-input/__tests__/element.test.js
  plugins/events-pro/src/modules/elements/number-input/element.js
Labels: review:merge

#354 Resolve general problems with Tickets Block Styles
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/advanced-options/duration/style.pcss
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/capacity/style.pcss
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/style.pcss
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/style.pcss
  plugins/tickets/src/modules/blocks/ticket/style.pcss
  plugins/tickets/src/modules/blocks/tickets/availability/style.pcss
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  plugins/tickets/src/modules/elements/action-dashboard/style.pcss
  plugins/tickets/src/modules/elements/container-panel/style.pcss
  plugins/tickets/src/modules/elements/label-with-tooltip/style.pcss
Labels: review:merge

#357 Removes `_edd_button_behavior` key from REST API
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/Tribe/Provider.php
Labels: review:merge

#358 Fix/timepicker issue when empty
  plugins/common/src/modules/elements/time-picker/element.js
  plugins/tickets/src/modules/blocks/rsvp/duration-picker/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/advanced-options/duration/container.js
Labels: status:code-review

#359 Prevent false positives on `disable_metabox_custom_fields` option
  plugins/events/src/Tribe/Editor.php
  readme.md
Labels: review:merge

#360 Prevent ticket creations if no provider is present
  package-lock.json
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/container.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/template.js
  plugins/tickets/src/modules/blocks/tickets/action-dashboard/container.js
  plugins/tickets/src/modules/blocks/tickets/action-dashboard/template.js
  plugins/tickets/src/modules/blocks/tickets/container/container.js
  plugins/tickets/src/modules/blocks/tickets/container/template.js
  plugins/tickets/src/modules/blocks/tickets/controls/container.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
Labels: review:merge

#361 Prevent endpoint setup if Tickets is disabled
  plugins/tickets/src/Tribe/REST/V1/Service_Provider.php
Labels: review:merge

#362 Time Selection + Border Style fixing for RSVP and Tickets block
  plugins/tickets/src/Tribe/Blocks/Tickets.php
  plugins/tickets/src/modules/blocks/rsvp/container/style.pcss
  plugins/tickets/src/modules/blocks/rsvp/duration/style.pcss
  plugins/tickets/src/modules/blocks/ticket/display-container/display/style.pcss
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/advanced-options/duration/style.pcss
  plugins/tickets/src/modules/blocks/tickets/container/style.pcss
  plugins/tickets/src/modules/elements/action-dashboard/style.pcss
  plugins/tickets/src/modules/elements/container-panel/style.pcss
  plugins/tickets/src/modules/elements/settings-dashboard/style.pcss
Labels: review:merge

#363 Passing Post ID into RSVP and Tickets views
  plugins/tickets/src/Tribe/Blocks/Rsvp.php
  plugins/tickets/src/Tribe/Blocks/Tickets.php
Labels: review:merge

#365 fix ticket create error
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ticket.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
Labels: review:merge

#367 Fix/ticket save error default
  plugins/tickets/src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/index.js
Labels: review:merge

#371 Make sure object properties match object destruct operation
  plugins/events/src/modules/blocks/event-datetime/container.js
  readme.md
Labels: status:code-review

#372 Prevent reset of times for an event when set from time picker
  plugins/events/src/modules/blocks/event-datetime/container.js
  plugins/events/src/modules/data/blocks/datetime/thunks.js
  readme.md
Labels: review:merge

#369 Feature/113380 multi day checkbox
  plugins/common/src/modules/elements/button/element.js
  plugins/common/src/modules/elements/checkbox-input/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/checkbox-input/__tests__/element.test.js
  plugins/common/src/modules/elements/checkbox-input/element.js
  plugins/common/src/modules/elements/checkbox-input/style.pcss
  plugins/common/src/modules/elements/checkbox/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/checkbox/__tests__/element.test.js
  plugins/common/src/modules/elements/checkbox/element.js
  plugins/common/src/modules/elements/checkbox/style.pcss
  plugins/common/src/modules/elements/image/element.js
  plugins/common/src/modules/elements/input/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/input/__tests__/element.test.js
  plugins/common/src/modules/elements/input/element.js
  plugins/common/src/modules/elements/input/style.pcss
  plugins/common/src/modules/elements/number-input/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/number-input/__tests__/element.test.js
  plugins/common/src/modules/elements/number-input/element.js
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/input/style.pcss
  plugins/events-pro/src/modules/elements/multi-day-checkbox/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/elements/multi-day-checkbox/__tests__/element.test.js
  plugins/events-pro/src/modules/elements/multi-day-checkbox/element.js
Labels: review:merge

#373 Feature/recurrence series end
  package-lock.json
  package.json
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/select/__tests__/element.test.js
  plugins/common/src/modules/elements/select/element.js
  plugins/common/src/modules/elements/select/style.pcss
  plugins/events-pro/src/modules/data/blocks/recurring/constants.js
  plugins/events-pro/src/modules/data/blocks/recurring/options.js
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/label/element.js
  plugins/events-pro/src/modules/elements/label/style.pcss
  plugins/events-pro/src/modules/elements/multi-day-checkbox/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/multi-day-checkbox/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/series-ends/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/series-ends/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/series-ends/element.js
Labels: review:merge

#374 Feature/115758 day of week picker
  plugins/common/src/modules/elements/checkbox/element.js
  plugins/events-pro/src/modules/data/blocks/recurring/constants.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/elements/day-of-week-picker/__tests__/element.test.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/__tests__/element.test.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/element.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/style.pcss
  plugins/events-pro/src/modules/elements/day-of-week-picker/element.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/style.pcss
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/on-day-of-week/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/on-day-of-week/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/on-day-of-week/element.js
Labels: review:merge

#375 Feature/115754 recurring to date time picker
  plugins/common/src/modules/elements/day-picker-input/element.js
  plugins/common/src/modules/elements/day-picker-input/style.pcss
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/input/style.pcss
  plugins/events-pro/src/modules/data/blocks/recurring/constants.js
  plugins/events-pro/src/modules/data/blocks/recurring/options.js
  plugins/events-pro/src/modules/elements/date-picker-input/element.js
  plugins/events-pro/src/modules/elements/date-picker-input/style.pcss
  plugins/events-pro/src/modules/elements/day-of-month-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/day-of-month-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/day-of-month-picker/element.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/element.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/element.js
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/multi-day-checkbox/element.js
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/element.js
  plugins/events-pro/src/modules/elements/series-ends/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/series-ends/element.js
  plugins/events/src/modules/elements/date-picker/element.js
  plugins/events/src/modules/elements/date-picker/style.pcss
  plugins/events/src/modules/elements/index.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/content/advanced-options/duration/__tests__/__snapshots__/template.test.js.snap
  plugins/tickets/src/modules/elements/date-time-range-picker/element.js
  plugins/tickets/src/modules/elements/date-time-range-picker/style.pcss
Labels: review:merge

#376 Feature/115755 single to date time picker
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/element.js
Labels: review:merge

#379 Prevent errors when saving a meta ticket
  plugins/events/src/Tribe/Template/Overwrite.php
  plugins/tickets/src/modules/blocks/tickets/container.js
  readme.md
Labels: review:merge

#378 Feature/115756 from time range picker
  plugins/common/src/modules/elements/select/style.pcss
  plugins/events-pro/src/modules/elements/day-of-month-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/day-of-month-picker/element.js
  plugins/events-pro/src/modules/elements/day-of-month-picker/style.pcss
  plugins/events-pro/src/modules/elements/from-time-range-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/from-time-range-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/element.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/style.pcss
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/label/style.pcss
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/element.js
  plugins/events-pro/src/modules/elements/series-ends/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/series-ends/element.js
  plugins/events-pro/src/modules/elements/series-ends/style.pcss
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/element.js
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/style.pcss
Labels: review:merge

#380 Load Going an Not Going values on the RSVP block
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/Tribe/REST/Compatibility.php
  plugins/tickets/src/modules/blocks/rsvp/container-header/container.js
  plugins/tickets/src/modules/blocks/rsvp/container-header/template.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/sagas.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/data/blocks/rsvp/thunks.js
  plugins/tickets/src/modules/elements/numeric-label/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/numeric-label/__tests__/element.test.js
  plugins/tickets/src/modules/elements/numeric-label/element.js
  readme.md
Labels: review:merge

#382 Feature/115884 month picker
  plugins/events-pro/src/modules/data/blocks/recurring/constants.js
  plugins/events-pro/src/modules/data/blocks/recurring/options.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/from-time-range-picker/element.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/style.pcss
  plugins/events-pro/src/modules/elements/in-month/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/in-month/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/in-month/element.js
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/labeled-row/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/labeled-row/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/labeled-row/element.js
  plugins/events-pro/src/modules/elements/labeled-row/style.pcss
  plugins/events-pro/src/modules/elements/month-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/month-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/month-picker/element.js
  plugins/events-pro/src/modules/elements/month-picker/month-tag/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/month-picker/month-tag/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/month-picker/month-tag/element.js
  plugins/events-pro/src/modules/elements/month-picker/month-tag/style.pcss
  plugins/events-pro/src/modules/elements/month-picker/style.pcss
  plugins/events-pro/src/modules/elements/on-day-of-week/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/on-day-of-week/element.js
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/element.js
  plugins/events-pro/src/modules/elements/series-ends/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/series-ends/element.js
  plugins/events-pro/src/modules/elements/series-ends/style.pcss
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/element.js
  plugins/events-pro/src/modules/elements/single-to-date-time-picker/style.pcss
Labels: review:merge

#381 Render "Not Going" button based on `meta` field
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/data/blocks/rsvp/thunks.js
  plugins/tickets/src/views/blocks/rsvp/status/not-going.php
  readme.md
Labels: review:merge

#377 Sync human readable input with UI
  __mocks__/chrono-node.js
  package-lock.json
  package.json
  plugins/common/src/modules/utils/__tests__/date.test.js
  plugins/common/src/modules/utils/__tests__/moment.test.js
  plugins/common/src/modules/utils/date.js
  plugins/common/src/modules/utils/moment.js
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/__tests__/__snapshots__/template.test.js.snap
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/__tests__/template.test.js
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/container.js
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/style.pcss
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/template.js
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/__snapshots__/thunks.test.js.snap
  plugins/events/src/modules/data/blocks/datetime/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/datetime/index.js
  plugins/events/src/modules/data/blocks/datetime/sagas.js
  plugins/events/src/modules/data/blocks/datetime/thunks.js
  plugins/events/src/modules/data/blocks/sagas.js
  plugins/events/src/modules/elements/date-input/__tests__/__snapshots__/element.test.js.snap
  plugins/events/src/modules/elements/date-input/__tests__/element.test.js
  plugins/events/src/modules/elements/date-input/element.js
  plugins/events/src/modules/elements/date-input/style.pcss
  plugins/events/src/modules/elements/index.js
  readme.md
Labels: review:merge

#386 Fix Venue selection on the Venue block
  plugins/events/src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
  plugins/events/src/modules/data/blocks/venue/reducer.js
  plugins/events/src/modules/data/blocks/venue/sagas.js
  plugins/events/src/modules/data/blocks/venue/utils.js
  readme.md
Labels: review:merge

#389 Adjust vertical alignment of the price section for the classic event datetime block
  plugins/events/src/modules/blocks/event-datetime/style.pcss
  readme.md
Labels: review:merge

#391 Branch used to sync `master` into `task/additional-fields`
  __mocks__/chrono-node.js
  events-gutenberg.php
  package-lock.json
  package.json
  plugins/common/package.json
  plugins/common/src/modules/utils/__tests__/date.test.js
  plugins/common/src/modules/utils/__tests__/moment.test.js
  plugins/common/src/modules/utils/date.js
  plugins/common/src/modules/utils/moment.js
  plugins/events-pro/package.json
  plugins/events/package.json
  plugins/events/src/Tribe/Editor.php
  plugins/events/src/Tribe/Template/Overwrite.php
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/__tests__/__snapshots__/template.test.js.snap
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/__tests__/template.test.js
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/container.js
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/style.pcss
  plugins/events/src/modules/blocks/event-datetime/human-readable-input/template.js
  plugins/events/src/modules/blocks/event-datetime/style.pcss
  plugins/events/src/modules/blocks/event-datetime/template.js
  plugins/events/src/modules/data/blocks/datetime/__tests__/__snapshots__/thunks.test.js.snap
  plugins/events/src/modules/data/blocks/datetime/__tests__/sagas.test.js
  plugins/events/src/modules/data/blocks/datetime/index.js
  plugins/events/src/modules/data/blocks/datetime/sagas.js
  plugins/events/src/modules/data/blocks/datetime/thunks.js
  plugins/events/src/modules/data/blocks/sagas.js
  plugins/events/src/modules/data/blocks/venue/__tests__/__snapshots__/reducer.test.js.snap
  plugins/events/src/modules/data/blocks/venue/reducer.js
  plugins/events/src/modules/data/blocks/venue/sagas.js
  plugins/events/src/modules/data/blocks/venue/utils.js
  plugins/events/src/modules/elements/date-input/__tests__/__snapshots__/element.test.js.snap
  plugins/events/src/modules/elements/date-input/__tests__/element.test.js
  plugins/events/src/modules/elements/date-input/element.js
  plugins/events/src/modules/elements/date-input/style.pcss
  plugins/events/src/modules/elements/index.js
  plugins/tickets/package.json
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Meta.php
  plugins/tickets/src/Tribe/REST/Compatibility.php
  plugins/tickets/src/modules/blocks/rsvp/container-header/container.js
  plugins/tickets/src/modules/blocks/rsvp/container-header/template.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/tickets/container.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/sagas.js
  plugins/tickets/src/modules/data/blocks/rsvp/selectors.js
  plugins/tickets/src/modules/data/blocks/rsvp/thunks.js
  plugins/tickets/src/modules/elements/numeric-label/__tests__/__snapshots__/element.test.js.snap
  plugins/tickets/src/modules/elements/numeric-label/__tests__/element.test.js
  plugins/tickets/src/modules/elements/numeric-label/element.js
  plugins/tickets/src/views/blocks/rsvp/status/not-going.php
  readme.md
  readme.txt
Labels: review:merge

#390 Add Checkbox to "show/hide" custom fields in Gutenberg Editor
  .editorconfig
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Template/Admin.php
  plugins/events-pro/src/admin-view/custom-fields/gutenberg.php
  plugins/events-pro/src/modules/admin-custom-fields/index.js
  plugins/events-pro/src/styles/admin/custom-fields.js
  plugins/events-pro/src/styles/admin/custom-fields.pcss
Labels: review:merge

#393 Feature/116023 116024 actions sagas selectors
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/__snapshots__/actions.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/__snapshots__/reducer.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/actions.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/reducer.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/actions.js
  plugins/events-pro/src/modules/data/blocks/exception/options.js
  plugins/events-pro/src/modules/data/blocks/exception/reducer.js
  plugins/events-pro/src/modules/data/blocks/exception/sagas.js
  plugins/events-pro/src/modules/data/blocks/exception/selectors.js
  plugins/events-pro/src/modules/data/blocks/exception/types.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/actions.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/reducer.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/actions.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/reducer.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/sagas.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/reducer.js
  plugins/events-pro/src/modules/data/blocks/recurring/sagas.js
  plugins/events-pro/src/modules/data/blocks/recurring/types.js
  plugins/events-pro/src/modules/elements/exception-field/element.js
  plugins/events-pro/src/modules/elements/exception-field/singular.js
  plugins/events-pro/src/modules/elements/exception-form/element.js
  plugins/events-pro/src/modules/elements/recurring-field/element.js
  plugins/events-pro/src/modules/elements/recurring-form/element.js
Labels: review:merge

#395 Register the new category for 'additional fields'
  plugins/events-pro/src/Tribe/Editor.php
Labels: review:merge

#396 Use 'additional-fields' in the assets instead of 'custom-fields'
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/modules/admin-additional-fields/index.js
  plugins/events-pro/src/styles/admin/additional-fields.js
  plugins/events-pro/src/styles/admin/additional-fields.pcss
  plugins/events-pro/src/styles/admin/custom-fields.js
Labels: review:merge

#397 Add `<Placeholder>` component used on Additional Fields
  plugins/events-pro/src/Tribe/Assets.php
  plugins/events-pro/src/modules/blocks/additional-fields/elements/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/placeholder/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/blocks/additional-fields/elements/placeholder/__tests__/element.test.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/placeholder/element.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/placeholder/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
  plugins/events-pro/src/modules/blocks/index.js
Labels: review:merge

#402 Update reference to a new location of the store
  plugins/tickets/src/modules/data/index.js
Labels: review:merge, status:code-review

#398 Add Preview component
  plugins/common/src/modules/elements/heading/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/heading/__tests__/element.test.js
  plugins/common/src/modules/elements/heading/element.js
  plugins/common/src/modules/elements/heading/style.pcss
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/paragraph/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/paragraph/__tests__/element.test.js
  plugins/common/src/modules/elements/paragraph/element.js
  plugins/common/src/modules/elements/paragraph/style.pcss
  plugins/common/src/modules/elements/placeholder/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/placeholder/__tests__/element.test.js
  plugins/common/src/modules/elements/placeholder/element.js
  plugins/common/src/modules/elements/placeholder/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/elements/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/preview/__tests__/__snapshots__/element.test.js.snap
  plugins/events-pro/src/modules/blocks/additional-fields/elements/preview/__tests__/element.test.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/preview/element.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/preview/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
Labels: review:merge

#400 Add styles for the input types on Edit Container
  package-lock.json
  package.json
  plugins/common/src/modules/elements/index.js
  plugins/common/src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
  plugins/common/src/modules/elements/select/__tests__/element.test.js
  plugins/common/src/modules/elements/select/element.js
  plugins/common/src/modules/elements/select/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/elements/edit-container/element.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/edit-container/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/elements/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
Labels: review:merge

#405 Make sure the ticket block uses the currency from the ticket provider
  plugins/common/src/modules/utils/__tests__/__snapshots__/globals.test.js.snap
  plugins/common/src/modules/utils/__tests__/globals.test.js
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/modules/blocks/ticket/display-container/display/container.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/__tests__/__snapshots__/template.tests.js.snap
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/actions.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ticket.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/tickets.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  plugins/tickets/src/modules/data/blocks/ticket/types.js
  plugins/tickets/src/modules/data/utils.js
  readme.md
Labels: review:merge

#410 Fix release issues
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/data/utils.js
Labels: status:code-review

#406 Feature/114600 ui exclusion rules 2
  plugins/common/src/modules/data/plugins/index.js
  plugins/common/src/modules/data/plugins/proptypes.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/container.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/template.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/container.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/template.js
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/actions.js
  plugins/events-pro/src/modules/data/blocks/exception/options.js
  plugins/events-pro/src/modules/data/blocks/exception/selectors.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/elements/day-of-month-picker/element.js
  plugins/events-pro/src/modules/elements/exception-field/daily.js
  plugins/events-pro/src/modules/elements/exception-field/element.js
  plugins/events-pro/src/modules/elements/exception-field/monthly.js
  plugins/events-pro/src/modules/elements/exception-field/singular.js
  plugins/events-pro/src/modules/elements/exception-field/weekly.js
  plugins/events-pro/src/modules/elements/exception-field/yearly.js
  plugins/events-pro/src/modules/elements/exception-form/element.js
  plugins/events-pro/src/modules/elements/index.js
  plugins/events-pro/src/modules/elements/recurring-field/daily.js
  plugins/events-pro/src/modules/elements/recurring-field/element.js
  plugins/events-pro/src/modules/elements/recurring-field/monthly.js
  plugins/events-pro/src/modules/elements/recurring-field/singular.js
  plugins/events-pro/src/modules/elements/recurring-field/weekly.js
  plugins/events-pro/src/modules/elements/recurring-field/yearly.js
  plugins/events-pro/src/modules/elements/recurring-form/element.js
  plugins/events-pro/src/modules/elements/series-ends/element.js
  plugins/events-pro/src/modules/elements/type-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/type-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/type-picker/element.js
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/element.js
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/style.pcss
  plugins/events-pro/src/modules/elements/type-picker/style.pcss
Labels: review:merge

#409 Sync with latest release from `master`
  events-gutenberg.php
  package-lock.json
  package.json
  plugins/common/package.json
  plugins/common/src/modules/utils/__tests__/__snapshots__/globals.test.js.snap
  plugins/common/src/modules/utils/__tests__/globals.test.js
  plugins/events-pro/package.json
  plugins/events/package.json
  plugins/events/src/Tribe/Editor.php
  plugins/tickets/package.json
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/modules/blocks/ticket/display-container/display/container.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/__tests__/__snapshots__/template.tests.js.snap
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/container.js
  plugins/tickets/src/modules/blocks/ticket/edit-container/header/template.js
  plugins/tickets/src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/actions.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  plugins/tickets/src/modules/data/blocks/ticket/reducers/ticket.js
  plugins/tickets/src/modules/data/blocks/ticket/reducers/tickets.js
  plugins/tickets/src/modules/data/blocks/ticket/sagas.js
  plugins/tickets/src/modules/data/blocks/ticket/selectors.js
  plugins/tickets/src/modules/data/blocks/ticket/types.js
  plugins/tickets/src/modules/data/utils.js
  readme.md
  readme.txt
Labels: status:code-review

#403 Add <Settings> component
  __mocks__/@wordpress/components.js
  __mocks__/@wordpress/editor.js
  package-lock.json
  package.json
  plugins/common/src/modules/utils/__tests__/string.test.js
  plugins/common/src/modules/utils/string.js
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/modules/blocks/additional-fields/elements/edit-container/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/elements/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/__tests__/__snapshots__/template.test.js.snap
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/__tests__/template.test.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
  plugins/tickets/src/modules/blocks/ticket/display-container/display/template.js
Labels: review:merge

#404 Add wrapper for <Settings> component for `checkbox` type of fields
  plugins/common/src/modules/utils/__tests__/string.test.js
  plugins/common/src/modules/utils/string.js
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/settings.js
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/style.pcss
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/__tests__/__snapshots__/template.test.js.snap
  plugins/events-pro/src/modules/blocks/additional-fields/elements/settings/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
Labels: review:merge

#407 Add shape for additional fields reducers in store
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/__snapshots__/actions.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/actions.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/selectors.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/types.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/utils.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/actions.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/index.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/field.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/fields.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/field.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/fields.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/field.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/fields.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/index.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/selectors.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/types.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/utils.js
  plugins/events-pro/src/modules/data/blocks/index.js
  plugins/events-pro/src/modules/data/blocks/reducer.js
  plugins/events-pro/src/modules/data/prefix.js
  plugins/events-pro/src/modules/data/reducers.js
Labels: review:merge

#413 Feature/116023 connect recurrence data 2
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/constants.js
  plugins/events-pro/src/modules/data/blocks/recurring/sagas.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/elements/exception-field/daily.js
  plugins/events-pro/src/modules/elements/exception-field/element.js
  plugins/events-pro/src/modules/elements/exception-field/monthly.js
  plugins/events-pro/src/modules/elements/exception-field/singular.js
  plugins/events-pro/src/modules/elements/exception-field/weekly.js
  plugins/events-pro/src/modules/elements/exception-field/yearly.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/element.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/template.js
  plugins/events-pro/src/modules/elements/recurring-field/daily.js
  plugins/events-pro/src/modules/elements/recurring-field/monthly.js
  plugins/events-pro/src/modules/elements/recurring-field/singular.js
  plugins/events-pro/src/modules/elements/recurring-field/weekly.js
  plugins/events-pro/src/modules/elements/recurring-field/yearly.js
  plugins/events-pro/src/modules/elements/series-ends/element.js
Labels: hold, status:code-review

#411 Abstract Field component for multiple field types
  plugins/common/src/modules/utils/__tests__/string.test.js
  plugins/common/src/modules/utils/string.js
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/dropdown/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/dropdown/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/field-container/element.js
  plugins/events-pro/src/modules/blocks/additional-fields/elements/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/radio/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/radio/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/text-area/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/text-area/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/text/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/text/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/url/index.js
  plugins/events-pro/src/modules/blocks/additional-fields/url/template.js
Labels: review:merge

#419 Register Meta for Recurrence on blocks editor
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/Tribe/Provider.php
Labels: status:code-review

#418 Feature/exclusions
  plugins/events-pro/src/modules/data/blocks/exception/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/blocks/exception/reducer.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/reducer.js
  plugins/events-pro/src/modules/elements/exception-field/monthly.js
  plugins/events-pro/src/modules/elements/exception-field/singular.js
  plugins/events-pro/src/modules/elements/exception-field/weekly.js
  plugins/events-pro/src/modules/elements/exception-field/yearly.js
  plugins/events-pro/src/modules/elements/in-month/element.js
  plugins/events-pro/src/modules/elements/month-picker/style.pcss
Labels: status:code-review

#422 Feature/store connection
  plugins/events-pro/src/modules/blocks/recurrence-exception/container.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/index.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/template.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/container.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/index.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/template.js
  plugins/events-pro/src/modules/blocks/recurrence/container.js
  plugins/events-pro/src/modules/blocks/recurrence/index.js
  plugins/events-pro/src/modules/blocks/recurrence/template.js
  plugins/events-pro/src/modules/data/blocks/exception/actions.js
  plugins/events-pro/src/modules/data/blocks/exception/reducer.js
  plugins/events-pro/src/modules/data/blocks/exception/selectors.js
  plugins/events-pro/src/modules/data/blocks/exception/types.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/reducer.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/data/blocks/recurring/types.js
  plugins/events-pro/src/modules/data/blocks/sagas.js
  plugins/events-pro/src/modules/data/shared/sync.js
  plugins/events-pro/src/modules/elements/attribute-sync/element.js
  plugins/events-pro/src/modules/elements/attribute-sync/template.js
Labels: review:merge

#414 Add attendees block.
  plugins/tickets/src/Tribe/Blocks/Attendees.php
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Provider.php
  plugins/tickets/src/modules/blocks/attendees/container.js
  plugins/tickets/src/modules/blocks/attendees/index.js
  plugins/tickets/src/modules/blocks/attendees/style.pcss
  plugins/tickets/src/modules/blocks/attendees/template.js
  plugins/tickets/src/modules/blocks/index.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/__snapshots__/reducer.test.js.snap
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/reducer.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/attendees/actions.js
  plugins/tickets/src/modules/data/blocks/attendees/index.js
  plugins/tickets/src/modules/data/blocks/attendees/reducer.js
  plugins/tickets/src/modules/data/blocks/attendees/sagas.js
  plugins/tickets/src/modules/data/blocks/attendees/selectors.js
  plugins/tickets/src/modules/data/blocks/attendees/types.js
  plugins/tickets/src/modules/data/blocks/reducer.js
  plugins/tickets/src/modules/data/blocks/sagas.js
  plugins/tickets/src/modules/icons/gravatar.svg
  plugins/tickets/src/modules/icons/index.js
  plugins/tickets/src/styles/attendees/frontend.js
  plugins/tickets/src/styles/attendees/frontend.pcss
  plugins/tickets/src/views/blocks/attendees.php
  plugins/tickets/src/views/blocks/attendees/description.php
  plugins/tickets/src/views/blocks/attendees/gravatar.php
  plugins/tickets/src/views/blocks/attendees/title.php
  readme.md
Labels: review:merge

#417 Register additional fields into the WP Rest API
  plugins/common/src/Tribe/Meta.php
  plugins/common/src/Tribe/Meta_Interface.php
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events/src/Tribe/Meta.php
  plugins/tickets/src/Tribe/Meta.php
Labels: review:merge

#425 CSS compatibility with Gutenberg 4.1 + Allow past years on Selection
  plugins/events/src/modules/blocks/style.pcss
  plugins/events/src/modules/elements/year-month-form/element.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  plugins/tickets/src/modules/elements/action-dashboard/style.pcss
  plugins/tickets/src/modules/elements/settings-dashboard/style.pcss
  readme.md
Labels: review:merge

#420 Save data from store into the post
  plugins/common/src/Tribe/Meta.php
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/Tribe/Meta.php
  plugins/events-pro/src/modules/blocks/additional-fields/dropdown/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/utils.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/__snapshots__/actions.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/sagas.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/field.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/fields.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/field.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/sagas.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/selectors.js
Labels: review:merge

#429 Add in syncing of timezone to recurrence rules and exceptions when ev…
  plugins/events-pro/src/modules/data/blocks/exception/sagas.js
  plugins/events-pro/src/modules/data/blocks/recurring/sagas.js
  plugins/events-pro/src/modules/data/shared/sagas.js
Labels: status:code-review

#426 Feature/fix elements 2
  plugins/events-pro/src/modules/blocks/recurrence-exception/container.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/index.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/template.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/container.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/index.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/template.js
  plugins/events-pro/src/modules/blocks/recurrence/container.js
  plugins/events-pro/src/modules/blocks/recurrence/index.js
  plugins/events-pro/src/modules/blocks/recurrence/template.js
  plugins/events-pro/src/modules/data/blocks/constants.js
  plugins/events-pro/src/modules/data/blocks/exception/actions.js
  plugins/events-pro/src/modules/data/blocks/exception/reducer.js
  plugins/events-pro/src/modules/data/blocks/exception/selectors.js
  plugins/events-pro/src/modules/data/blocks/exception/types.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/reducer.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/data/blocks/recurring/types.js
  plugins/events-pro/src/modules/data/blocks/sagas.js
  plugins/events-pro/src/modules/data/shared/sagas.js
  plugins/events-pro/src/modules/data/shared/selectors.js
  plugins/events-pro/src/modules/data/shared/sync.js
  plugins/events-pro/src/modules/elements/attribute-sync/element.js
  plugins/events-pro/src/modules/elements/attribute-sync/template.js
  plugins/events-pro/src/modules/elements/recurring-to-date-time-picker/element.js
Labels: status:code-review

#427 Render views for the additional fields
  plugins/common/src/Tribe/Blocks/Abstract.php
  plugins/events-pro/src/Tribe/Additional_Fields.php
  plugins/events-pro/src/Tribe/Blocks/Additional_Field.php
  plugins/events-pro/src/Tribe/Blocks/Additional_Fields.php
  plugins/events-pro/src/Tribe/Editor.php
  plugins/events-pro/src/Tribe/Provider.php
  plugins/events-pro/src/Tribe/Template/Frontend.php
  plugins/events-pro/src/modules/blocks/additional-fields/checkbox/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/dropdown/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/radio/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/radio/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/text-area/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/text/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/text/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/url/container.js
  plugins/events-pro/src/modules/blocks/additional-fields/url/template.js
  plugins/events-pro/src/modules/blocks/additional-fields/utils.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/__snapshots__/actions.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/actions.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/sagas.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/__tests__/types.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/actions.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/field.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/__snapshots__/fields.test.js.snap
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/__tests__/field.test.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/field.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/reducers/fields.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/sagas.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/selectors.js
  plugins/events-pro/src/modules/data/blocks/additional-fields/types.js
  plugins/events-pro/src/views/blocks/additional-fields/checkbox.php
  plugins/events-pro/src/views/blocks/additional-fields/dropdown.php
  plugins/events-pro/src/views/blocks/additional-fields/radio.php
  plugins/events-pro/src/views/blocks/additional-fields/text.php
  plugins/events-pro/src/views/blocks/additional-fields/textarea.php
  plugins/events-pro/src/views/blocks/additional-fields/url.php
Labels: status:code-review

#431 Feature/113422 rule exclusion count
  plugins/events-pro/src/modules/blocks/recurrence-exception/container.js
  plugins/events-pro/src/modules/blocks/recurrence-exception/template.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/container.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/template.js
  plugins/events-pro/src/modules/data/blocks/exception/selectors.js
  plugins/events-pro/src/modules/data/blocks/recurring/selectors.js
  plugins/events-pro/src/modules/elements/exception-form/element.js
  plugins/events-pro/src/modules/elements/panel-header/element.js
  plugins/events-pro/src/modules/elements/panel-header/style.pcss
  plugins/events-pro/src/modules/elements/panel/element.js
Labels: review:merge

#439 Add quotation marks
  plugins/tickets/src/modules/blocks/rsvp/container-content/template.js
Labels: review:merge

#433 #116130 wording tweak
  plugins/tickets/src/modules/blocks/tickets/container/template.js
Labels: review:merge

#432 Block description punctuation
  plugins/events/src/modules/blocks/classic-event-details/index.js
  plugins/tickets/src/modules/blocks/attendees/index.js
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/ticket/index.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/index.js
Labels: review:merge

#438 Fix/113420 add missing recurrence tests
  plugins/events-pro/src/modules/data/blocks/__tests__/constants.spec.js
  plugins/events-pro/src/modules/data/blocks/constants.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/actions.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/constants.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/options.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/reducer.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/__snapshots__/selectors.spec.js.snap
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/actions.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/constants.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/options.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/reducer.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/__tests__/types.spec.js
  plugins/events-pro/src/modules/data/blocks/recurring/actions.js
  plugins/events-pro/src/modules/data/blocks/recurring/options.js
  plugins/events-pro/src/modules/data/ui/__tests__/__snapshots__/actions.spec.js.snap
  plugins/events-pro/src/modules/data/ui/__tests__/__snapshots__/actions.test.js.snap
  plugins/events-pro/src/modules/data/ui/__tests__/__snapshots__/reducer.spec.js.snap
  plugins/events-pro/src/modules/data/ui/__tests__/__snapshots__/reducer.test.js.snap
  plugins/events-pro/src/modules/data/ui/__tests__/actions.spec.js
  plugins/events-pro/src/modules/data/ui/__tests__/actions.test.js
  plugins/events-pro/src/modules/data/ui/__tests__/reducer.spec.js
  plugins/events-pro/src/modules/data/ui/__tests__/reducer.test.js
  plugins/events-pro/src/modules/data/ui/__tests__/selectors.spec.js
  plugins/events-pro/src/modules/data/ui/__tests__/selectors.test.js
  plugins/events-pro/src/modules/data/ui/__tests__/type.spec.js
Labels: review:merge

#437 Sync `master` with task branch
  events-gutenberg.php
  package-lock.json
  package.json
  plugins/common/src/Tribe/Editor.php
  plugins/events/src/modules/blocks/event-venue/template.js
  plugins/events/src/modules/blocks/style.pcss
  plugins/events/src/modules/data/blocks/venue/utils.js
  plugins/events/src/modules/elements/search-or-create/style.pcss
  plugins/events/src/modules/elements/year-month-form/element.js
  plugins/tickets/src/Tribe/Blocks/Attendees.php
  plugins/tickets/src/Tribe/Editor.php
  plugins/tickets/src/Tribe/Provider.php
  plugins/tickets/src/modules/blocks/attendees/container.js
  plugins/tickets/src/modules/blocks/attendees/index.js
  plugins/tickets/src/modules/blocks/attendees/style.pcss
  plugins/tickets/src/modules/blocks/attendees/template.js
  plugins/tickets/src/modules/blocks/index.js
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/tickets/style.pcss
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/__snapshots__/reducer.test.js.snap
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/reducer.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/selectors.test.js
  plugins/tickets/src/modules/data/blocks/attendees/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/attendees/actions.js
  plugins/tickets/src/modules/data/blocks/attendees/index.js
  plugins/tickets/src/modules/data/blocks/attendees/reducer.js
  plugins/tickets/src/modules/data/blocks/attendees/sagas.js
  plugins/tickets/src/modules/data/blocks/attendees/selectors.js
  plugins/tickets/src/modules/data/blocks/attendees/types.js
  plugins/tickets/src/modules/data/blocks/reducer.js
  plugins/tickets/src/modules/data/blocks/sagas.js
  plugins/tickets/src/modules/data/utils.js
  plugins/tickets/src/modules/elements/action-dashboard/style.pcss
  plugins/tickets/src/modules/elements/settings-dashboard/style.pcss
  plugins/tickets/src/modules/icons/gravatar.svg
  plugins/tickets/src/modules/icons/index.js
  plugins/tickets/src/styles/attendees/frontend.js
  plugins/tickets/src/styles/attendees/frontend.pcss
  plugins/tickets/src/views/blocks/attendees.php
  plugins/tickets/src/views/blocks/attendees/description.php
  plugins/tickets/src/views/blocks/attendees/gravatar.php
  plugins/tickets/src/views/blocks/attendees/title.php
  readme.md
  readme.txt
Labels: status:code-review

#440 Escape boostrap script
  package-lock.json
  plugins/events-pro/scripts/linkDependencies
Labels: review:merge

#442 Fix/113420 add missing element tests
  plugins/common/src/modules/components/prevent-block-close/__tests__/component.spec.js
  plugins/events-pro/src/modules/elements/attribute-sync/__tests__/__snapshots__/template.spec.js.snap
  plugins/events-pro/src/modules/elements/attribute-sync/__tests__/template.spec.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/day-of-week-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/day-of-week-picker/day-of-week/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/fieldset/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/fieldset/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/from-time-range-picker/__tests__/template.spec.js
  plugins/events-pro/src/modules/elements/label/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/label/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/month-picker/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/on-day-of-week/template.js
  plugins/events-pro/src/modules/elements/panel-header/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/panel-header/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/panel/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/panel/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/remove-field/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/remove-field/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/remove-field/element.js
  plugins/events-pro/src/modules/elements/row/__tests__/__snapshots__/element.spec.js.snap
  plugins/events-pro/src/modules/elements/row/__tests__/element.spec.js
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/__tests__/__snapshots__/template.spec.js.snap
  plugins/events-pro/src/modules/elements/type-picker/frequency-select/__tests__/template.spec.js
Labels: review:merge

#441 Make sure Icon is a component and not an SVG
  plugins/events-pro/src/modules/blocks/recurrence-exception/index.js
  plugins/events-pro/src/modules/blocks/recurrence-rule/index.js
  plugins/events-pro/src/modules/blocks/recurrence/index.js
Labels: review:merge

#436 Add utility for PHP in common
  plugins/common/src/Tribe/Provider.php
  plugins/common/src/Tribe/Utils.php
  plugins/events-pro/src/Tribe/Additional_Fields.php
Labels: review:merge

#444 Fix limit not setting correctly
  plugins/events-pro/src/modules/data/shared/sagas.js
Labels: review:merge

#445 Fix/116907 timepicker styling disabled
  plugins/common/src/modules/elements/time-picker/style.pcss
  plugins/events-pro/src/modules/elements/from-time-range-picker/template.js
Labels: review:merge

#447 updating block icons
  plugins/common/src/modules/elements/block-icon/style.pcss
  plugins/events/src/modules/blocks/classic-event-details/index.js
  plugins/events/src/modules/blocks/event-category/index.js
  plugins/events/src/modules/blocks/event-datetime/index.js
  plugins/events/src/modules/blocks/event-links/index.js
  plugins/events/src/modules/blocks/event-organizer/index.js
  plugins/events/src/modules/blocks/event-price/index.js
  plugins/events/src/modules/blocks/event-tags/index.js
  plugins/events/src/modules/blocks/event-venue/index.js
  plugins/events/src/modules/blocks/event-website/index.js
  plugins/events/src/modules/blocks/featured-image/index.js
  plugins/events/src/modules/icons/categories.svg
  plugins/events/src/modules/icons/classic.svg
  plugins/events/src/modules/icons/date-time.svg
  plugins/events/src/modules/icons/featured-image.svg
  plugins/events/src/modules/icons/index.js
  plugins/events/src/modules/icons/organizer.svg
  plugins/events/src/modules/icons/price.svg
  plugins/events/src/modules/icons/sharing.svg
  plugins/events/src/modules/icons/tags.svg
  plugins/events/src/modules/icons/venue.svg
  plugins/events/src/modules/icons/website.svg
  plugins/tickets/src/modules/blocks/attendees/index.js
  plugins/tickets/src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/rsvp/action-buttons/attendees-action-button/template.js
  plugins/tickets/src/modules/blocks/rsvp/index.js
  plugins/tickets/src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  plugins/tickets/src/modules/blocks/tickets/action-buttons/attendees/template.js
  plugins/tickets/src/modules/blocks/tickets/action-buttons/orders/template.js
  plugins/tickets/src/modules/blocks/tickets/index.js
  plugins/tickets/src/modules/icons/attendees.svg
  plugins/tickets/src/modules/icons/index.js
  plugins/tickets/src/modules/icons/orders.svg
  plugins/tickets/src/modules/icons/rsvp.svg
  plugins/tickets/src/modules/icons/tickets.svg
Labels: review:merge

#446 Fix/117045 default sale date
  plugins/tickets/src/modules/blocks/rsvp/container.js
  plugins/tickets/src/modules/blocks/rsvp/template.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/__snapshots__/actions.test.js.snap
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/actions.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/__tests__/types.test.js
  plugins/tickets/src/modules/data/blocks/rsvp/actions.js
  plugins/tickets/src/modules/data/blocks/rsvp/sagas.js
  plugins/tickets/src/modules/data/blocks/rsvp/types.js
  readme.md
Labels: review:merge
