Repository moderntribe/events-gutenberg, pull requests merged in 2018-03, with the labels that each got.

#15 Improve Maps and Use static image properly
  package.json
  src/Tribe/Editor.php
  src/modules/blocks/event-venue/block.js
  src/modules/blocks/event-venue/venue.js
  src/modules/blocks/style.pcss
  src/modules/elements/google-static-map.js
  src/modules/elements/index.js
  src/modules/elements/map-container.js
  src/modules/elements/venue-map.js
Labels: code review, review:merge

#16 Always display actions for Organizers when it's empty
  src/modules/blocks/event-details/organizers.js
Labels: code review, review:merge

#23 Modify the PHP code to respect all the Block customizations
  events-gutenberg.php
  readme.md
  src/Tribe/Blocks/Abstract.php
  src/Tribe/Blocks/Event_Details.php
  src/Tribe/Blocks/Event_Subtitle.php
  src/Tribe/Blocks/Event_Venue.php
  src/Tribe/Blocks/Interface.php
  src/Tribe/Editor.php
  src/Tribe/Provider.php
  src/Tribe/Template.php
  src/Tribe/Template/Overwrite.php
  src/views/blocks/event-details.php
  src/views/blocks/event-subtitle.php
  src/views/blocks/event-venue.php
  src/views/blocks/parts/details.php
  src/views/blocks/parts/map.php
  src/views/blocks/parts/organizer.php
  src/views/blocks/parts/venue.php
  src/views/silence.php
  src/views/single-event.php
Labels: code review, review:merge

#30 block title and description update
  src/modules/blocks/event-links/index.js
Labels: type:question

#40 Spliting DateTime Picker into Two Elements
  package.json
  src/Tribe/Editor.php
  src/modules/blocks/event-details/block.js
  src/modules/blocks/event-subtitle/block.js
  src/modules/blocks/style.pcss
  src/modules/elements/datepicker.js
  src/modules/elements/index.js
  src/modules/elements/timepicker.js
Labels: review:merge, status:code-review
